### ISSUE TITLE
How to cite text in guidance?

### ISSUE THREAD

**Issue by Jiefei-Wang** [guidance-ai/guidance#1053]
This might be a silly question, but I cannot find the answer in the README file. Is there any way to cite the original text that the user provided? For example

```
[user]
Help me to extract the vital sign and cite the original text where you find the information: 
34 y/o male, John Doe, came in post-MVC (rollover) as a trauma transfer. HR 80, RR 16, T 98.6 F

[client]
{
    {"type": "heat rate", "value": "80", "text": "HR 80"}
    {"type": "respiratory rate", "value": "16", "text": "RR 16"}
    ....
}
```

I understand how to constrain the vital type and value using guidance. I'm trying to constrain the text data as well so the model would not give me any hallucination. Ideally, I need a function like `cite("A long long text that model might cite a piece from")`. Is there any function I can use in guidance? Thanks

**Comment by hudson-ai** [comment]
Hi @Jiefei-Wang, thanks for the question!

We have a function called "substring" (`from guidance import substring`) that you can use exactly as you describe. Just note that guidance won't guarantee the *semantic* meaning of the citation (i.e. that what is cited should be a small snippet of the original text that contains the information you just extracted, not just any random snippet from the original text) -- it's up to you to still craft a good prompt that communicates to the model what you want.

Let me know if you run into any further difficulty, and I'd be happy to help!

**Comment by Jiefei-Wang** [comment]
That is fantastic! I'll give it a try and let you know if I encounter any issues. Thanks a lot for highlighting this function for me!
