### ISSUE TITLE
Inconsistent (Worse) Output with Separate Generation Calls

### ISSUE THREAD

**Issue by cyclecycle** [guidance-ai/guidance#1079]
**The bug**

I'm experiencing inconsistent (worse) results when generating text in multiple separate calls versus a single continuous generation. Specifically, using repeated calls to `gen` or `select` leads to degraded output quality, compared to a single, unbroken call.

**To Reproduce**

Consider these two examples for a text cleaning/formatting task:

```python
# Setup

from guidance import models, gen

model_name = "wassname/llama-3-2-1b-sft"
lm = models.Transformers(model_name)
```

```python
# Example 1

input_msg = f"""
Clear up any formatting issues in this text:

Brinster, R. L., and Avarbock, M. R. (1994). Germline transmission of donor haplotype followingspermatogonial transplantation. Proc. Natl. Acad. Sci.USA 91, 11303–11307. doi:10.1073/pnas.91.24.11303 Brinster, R. L., and Zimmermann, J. W. (1994). Spermatogenesis following male germ-celltransplantation. Proc. Natl. Acad. Sci.USA 91, 11298–11302. doi:10.1073/pnas.

91.24.11298 Browning, L., Patel, M. R., Horvath, E. B., Tawara, K., and Jorcyk, C. L. (2018). IL-6 and ovarian cancer:inflammatory cytokines in promotion of metastasis. Cancer Manag.

Res. 5 (10), 6685–6693. doi:10.2147/CMAR.S179189 Cao, C., Zhao, J., Doughty, E. K., Migliorini, M., Strickland, D. K., Kann, M. G.,
et al. (2015). Mac-1 regulates IL-13 activity in macrophages by directly interacting with IL-13rα1. J. Biol. Chem. 290 (35), 21642–21651. doi:10.1074/
jbc.M115.645796 Cheng, J.-M., Tang, J.-X., Li, J., Wang, Y.-Q., Wang, -X.-X., Zhang, Y., et al. (2018).

Role of WNT signaling in epididymal sperm maturation. J. Assist. Reprod. Genet. 35, 229–236. doi:10.1007/s10815-017-1066-4

Cleaned up text:
"""

lm += input_msg
lm += gen("output", max_tokens=100)
```

This produces the following output:

```
Brinster, R. L., and Avarbock, M. R. (1994). Germline transmission of donor haplotype following permatogonial transplantation. Proc. Natl. Acad. Sci.USA 91, 11303–11307. doi:10.1073/pnas.91.24.11303

91.24.11303

Brinster, R. L., and Zimmermann, J. W. (
```

Now consider the same prompt but using a loop of shorter, nested completions for the same number of total tokens (50 x 2 rather than 100):

```python
# Example 2

lm.reset()
lm += input_msg

for i in range(50):
    lm += gen("output", max_tokens=2, list_append=True)
```

Which produces:

```
Brinsterr, R. L., and Avarbok, M. R. (1994). Germline transmission of donor haplotype following permatogonial transplantation. Proc. Natl. Acad. Sci.USA 91, 11303–11307. doi:10.1073/pnas.91.24.11303

91.24.11298 Browning, L., Patel, M. R., Horvath, E.
```

I would expect the output from this to be equal to the first but surprisingly it diverges from the above in two respects:
- The first word has an extra "r", which is weird
- On the second line it starts producing "Browning" instead of the correct "Brinster"

**Extra detail**

This is one example of degraded performance which seems to occur whenever using multiple smaller generation calls rather than one unbroken call.

For context, our use case involves dynamically constraining the next possible tokens during generation to prevent drifting away from valid options in the input, using a pattern like:

```
for i in range(n):
    options = get_next_options()
    lm += select(options)
```

We saw degraded output with this pattern, which led us to start investigating this behaviour.

**Questions**

- Is this behaviour expected when using multiple short generation calls instead of a single long one?
- Could this be due to token boundary issues or token healing features, and is there a way to deactivate or work around it?
- Are we misusing `select` in this context? What would be the intended approach for doing constrained decoding where the next possible options need to be dynamically updated as we progress through the generation?

**System info (please complete the following information):**
 - OS (Ubuntu)
 - Guidance Version: '0.1.16'
 
N.B. We've seen this degraded behaviour also with Llama 3.1 70B.

We'd be happy to help debug or improve this. Please let us know your thoughts. Thanks

**Comment by Harsha-Nori** [comment]
Hi @cyclecycle, 

Thanks for reporting this! I re-ran your example code on our main branch and it looks like it produces the exact same output now :). I suspect you caught a bug with our token healing logic that got fixed when we updated our parsing stack! 

```python
lm += input_msg
lm_manygen = lm
lm += gen("output", max_tokens=100, temperature=0)

# Example 2

for i in range(50):
    lm_manygen += gen("output", max_tokens=2, list_append=True, temperature=0)
```

<img width="511" alt="image" src="https://github.com/user-attachments/assets/6ae3934b-acae-4bb6-93a4-bd101c1e6ecf">


Would you mind upgrading guidance and trying your tests again? Would be great to know if we still have lingering issues with this. I suspect it's likely fixed with our latest release candidate as well (`pip install guidance --pre`), but we will be doing a new release to PyPI soon from main branch either way. 

-Harsha

**Comment by cyclecycle** [comment]
Hi @Harsha-Nori,

I can confirm that after upgrading to latest release candidate the manygen output is now equal to singlegen on my side too.

I will keep going with the many consecutive `select` use case. I can see that the behaviour has changed but I will need to do more work to verify whether it is behaving well. 

I will report back if I can share anything of interest.

Thanks for the your work and for the support. All the best

**Comment by Harsha-Nori** [comment]
Closing for now, but feel free to re-open if you notice any further issues!
