### ISSUE TITLE
Type Checker yells at me when I use guidance with arguments

### ISSUE THREAD

**Issue by ibehnam** [guidance-ai/guidance#111]
**The bug**
The message:

```
Module is not callablePyright[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
module guidance
(module) guidance
```

Example code used:

```
program = guidance("""Tweak this proverb to apply to model instructions instead.
                   
{{proverb}}
- {{book}} {{chapter}}:{{verse}}

UPDATED
Where there is no guidance{{gen 'rewrite' stop="\\n-"}}
- GPT {{gen 'chapter'}}:{{gen 'verse'}}""")
```

**Comment by slundberg** [comment]
Interesting. In this case that is not correct since the module is actually callable. Perhaps there is a way to add a comment that will override that for people using pyright?

**Comment by justinbowes** [comment]
My unfortunate workaround for this is:
`program: guidance.Program = guidance(...) # type: ignore`

While it's fluent in a singleton context, extending Module via the __class__ attribute is fundamentally an impolite thing to do. Obeying the convention that modules are `Modules` makes static analysis significantly easier. Tools like Pyright that are _not implemented in Python_ can't possibly model all of the effects that could result from dynamic module semantics (smells like halting problem to me).

https://discuss.python.org/t/pep-713-callable-modules/26127 is under consideration to address this in a different way (and https://discuss.python.org/t/pep-713-callable-modules/26127/59 is a counterproposal providing an example of your approach).

**Comment by marcotcr** [comment]
Hopefully this is gone in the new [release](https://github.com/guidance-ai/guidance/discussions/429) :)
Thanks for pointing this problem out!

**Comment by michael-newsrx** [comment]
I'm getting this error in pycharm.

![image](https://github.com/guidance-ai/guidance/assets/5214185/03256192-e659-4307-8f43-67febd935507)


How can I get this approach to work in pycharm?

```python
from guidance import Program


@Program(stateless=True)
def x(lm):
    return lm
```

results in:

```python
ImportError: cannot import name 'Program' from 'guidance'
```

and 

```python
import guidance


@guidance.Program(stateless=True)
def x(lm):
    return lm
```

results in:

```python
AttributeError: module 'guidance' has no attribute 'Program'
```

**Comment by tanders** [comment]
My workaround for this issue is to use something like @guidance.guidance instead. Pylance is happy with that, and this is also more in line with common Python practice.

```Python
import guidance as guide

@guide.guidance(dedent=False)
def qa_bot(lm, query):
    lm += f"""
    Q: {query}
    A: {guide.gen(name="answer", stop="Q:")}"""
    return lm

```
