### ISSUE TITLE
Add support for Vertex API PaLM models

### ISSUE THREAD

**Issue by pheuter** [guidance-ai/guidance#124]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use Google's PaLM models with Guidance via the new publicly available Vertex API

**Describe the solution you'd like**
For guidance to integrate with Vertex AI's text generation and chat models:
- [API](https://cloud.google.com/python/docs/reference/aiplatform/latest/vertexai.preview.language_models)
- [SDK](https://github.com/googleapis/python-aiplatform)

**Comment by slundberg** [comment]
Happy to review any PRs :)

**Comment by uripeled2** [comment]
Checkout llm-client, an open-source Python package for seamless integration with LLMs🌟
https://github.com/uripeled2/llm-client-sdk

**Comment by aswny** [comment]
+1 please add support for Google Palm models using MakerSuite API key

**Comment by colinappnovation** [comment]
+1

**Comment by rehanguha** [comment]
Hi, Is there any update on this issue as of now? or any alternatives?

**Comment by sundar-sarvam** [comment]
+1. Support for palm models will be useful!

**Comment by FCMHUB** [comment]
+1

**Comment by marcotcr** [comment]
Sorry it took us so long to get to this. In the new [release](https://github.com/guidance-ai/guidance/discussions/429), it's supported [(see this)](https://github.com/guidance-ai/guidance#vertex-ai)
