### ISSUE TITLE
multiple models

### ISSUE THREAD

**Issue by krrishdholakia** [guidance-ai/guidance#167]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to use different models in my prompt script - e.g. using chatGPT for generating reasoning and then gpt-3 to fill in the blanks.

**Comment by justinbowes** [comment]
I think you can do this using partials.

Imagine a template `main` that looks like this:

```python
main = guidance("""
{{#system}}
You are a helpful AI.
{{/system}}
{{#user}}
Provide a strategy for solving the following problem. Do not actually solve the problem, just outline the strategy
{{problem}}
{{/user}}
{{#assistant}}
{{gen 'strategies'}}
{{/assistant}}
{{>solver}}
""")
```

Also imagine a template `solver` that looks like this:

```python
solver = guidance("""
{{#user}}
Now given the strategy above, solve the problem.
{{/user}}
{{#assistant}}
{{gen 'solution'}}
{{/assistant}}
""")
```

You should be able to handle this with multiple LLMs as follows:

```python
reasoning_llm = guidance.llms.OpenAI("gpt-4")
executor_llm = guidance.llms.OpenAI("text-davinci-003") 
output = main(
    problem="How can I organize a conference?", 
    llm=reasoning_llm,
    solver=solver(
        llm=executor_llm
    )
)
```

I haven't done this personally, but I have worked with the partials system a little bit, and this looks like it falls within design intent.

**Comment by chiggly007** [comment]
having issues with my openai keys, but curious if anyone has tested this out?

**Comment by roy-pstr** [comment]
I must agree with the original request. The solution suggested here wit the partial even if it works I'd argue it fails on the readability. 
A proper syntax would be:
```
main = guidance("""
{{#system}}
You are a helpful AI.
{{/system}}
{{#user}}
Provide a strategy for solving the following problem. Do not actually solve the problem, just outline the strategy
{{problem}}
{{/user}}
{{#assistant}}
{{gen 'strategies' model=reasoning_llm}}
{{/assistant}}
{{#user}}
Now given the strategy above, solve the problem.
{{/user}}
{{#assistant}}
{{gen 'solution' model=executor_llm}}
{{/assistant}}
""")
```

**Comment by chiggly007** [comment]
yes this look way cleaner and easier to read. @marcotcr @slundberg  thoughts on this?

**Comment by faizanahemad** [comment]
@marcotcr @slundberg please check this out

**Comment by marcotcr** [comment]
This should be very easy to do in the new [release](https://github.com/guidance-ai/guidance/discussions/429), where each `lm` can be its own object :)
