### ISSUE TITLE
Unable to load model

### ISSUE THREAD

**Issue by Picus303** [guidance-ai/guidance#187]
(LLM beginner, I'm probably the issue but because I found no documentation except the ReadMe, I'm here)

**The bug**
When trying to load a model with an exemple from the ReadMe, I only get an infinite loading time.
Only one thread is used and nothing is loaded in the RAM. Nothing happens on the GPU.
The model : https://huggingface.co/decapoda-research/llama-7b-hf

It took me a few tries to find a model that works but after a lot of error messages, I think I installed all the dependences that aren't installed at the same time as Guidance (Pytorch, Tensorflow, Transformers...).

**To Reproduce**

```python
import guidance
guidance.llm = guidance.llms.Transformers(r"C:\path\to\models\llama-7b-hf", device=0)
```

**System info:**
 - OS : Windows 10
 - Guidance Version : 0.0.61
 - Anaconda + Jupyter lab
 - AMD Ryzen 5 5500
 - AMD Radeon RX 6800 XT

**Comment by marcotcr** [comment]
In the new [release](https://github.com/guidance-ai/guidance/discussions/429) we also support [llama.cpp](https://github.com/guidance-ai/guidance#llamacpp), which loads models much faster :)
