### ISSUE TITLE
Example Model can't load

### ISSUE THREAD

**Issue by linonetwo** [guidance-ai/guidance#202]
**The bug**

```py
import guidance
guidance.llm = guidance.llms.Transformers(r"C:\path\to\models\llama-7b-hf", device=0)
```

This runs for 30min+ with 2M/s download, and failed.

I think support openai API key in the example will solve this. (Many people try example before take time add openai integration by self. so maybe you need to provide this in your example.)

**To Reproduce**

Run the JSON syntax example jupyternotebook.

**System info (please complete the following information):**
 - OS Mac OS
 - Guidance Version : latest example

**Comment by marcotcr** [comment]
Please try the new [release](https://github.com/guidance-ai/guidance/discussions/429) -- we tested it extensively with a variety of huggingface and llama.cpp models, especially llama models :)
