### ISSUE TITLE
Improve `IncompleteParseError` message

### ISSUE THREAD

**Issue by jelling** [guidance-ai/guidance#207]
**Is your feature request related to a problem? Please describe.**

If a user creates a guidance program with a space in between the handlebars and the command like the space prior to "gen" here: 

```
{{ gen "out" n=3 max_tokens=75}}
```

The error returned is: 

> IncompleteParseError: Rule 'template' matched in its entirety, but it didn't consume all the text. The non-matching portion of the text begins with...

**Describe the solution you'd like**

A clearer error message like "Space detected between {{ and gen..." would be more helpful.

**Comment by marcotcr** [comment]
In the new [release](https://github.com/guidance-ai/guidance/discussions/429) we did away with handlebars, so hopefully this kind of issue does not present itself again. Sorry it took us so long to get to this :)
