### ISSUE TITLE
Advanced logic for controlled generation

### ISSUE THREAD

**Issue by EgorBu** [guidance-ai/guidance#236]
**Is your feature request related to a problem? Please describe.**
I want to use `guidance` for some kind of extractive summarization. Example - I have some code
```python
def some_function(arg1: type1, etc: etc_type) -> return_type:
    """Some docstring"""
    val1 = expr(arg1)
    val2 = expr(etc)
    val3 = expr(val1, val2)
    for i in [val1, val2, val3]:
        some_advanced_logic(i)
   some_logging()
   return result(val3)
```
and I want to extract some parts of this code using LLM like `expr(arg1)`,
```python
    val2 = expr(etc)
    val3 = expr(val1, val2)
```
, etc - these parts should be valid parts for extraction so I need to use external tools to verify correctness of extracted parts

**Describe the solution you'd like**
I'm not very familiar with API of `guidance` yet - but it looks like that it's similar to some kind of beam search
* start positions for generation (or equivalent possible tokens to start with)
* beams that goes further until reach condition `is_valid_expression` - but there should be another option like `can_continue` (like in case of several expressions on several lines)
* use cool features like logporbs, etc to select better variants of extracted parts

**Describe alternatives you've considered**
Implement beam search without cool features of `guidance`

**Additional context**
It would be really cool to have `guidance` for LLM training

**Comment by marcotcr** [comment]
This should be much easier with the new [release](https://github.com/guidance-ai/guidance/discussions/429), please check it out :)
