### ISSUE TITLE
Vicuna-7B returns incorrect choice

### ISSUE THREAD

**Issue by AndyJZhao** [guidance-ai/guidance#248]
**The bug**
Hi, thanks for the effort of developing this awesome library.
When I tried to use the select function on my local Vicuna-7B, the function is not working as expected, similar to #17.
However, there are two issues:
1. The selection content is not hidden.
2. Generated content is out of choices.

**To Reproduce**
```python
# Modified the official guide to load Vicuna-7B
vicuna_path = '/path/to/my/checkpoints/vicuna-7b/'
llm = guidance.llms.transformers.Vicuna(vicuna_path, device_map="auto")

program = guidance('''Is the following sentence offensive? Please answer with a single word, either "Yes", "No", or "Maybe".
Sentence: {{example}}
Answer:{{#select "answer" logprobs='logprobs'}} Yes{{or}} No{{or}} Maybe{{/select}}''', llm=llm)
executed_program = program(example='I hate tacos')
```

The returned result:
```
Is the following sentence offensive? Please answer with a single word, either "Yes", "No", or "Maybe".
Sentence: I hate tacos
Answer: Yes No Maybee Yes
```
Issue 1: The selection content is not hidden.
We can see that instead of generate the choice only, the choices are also returned.
![image](https://github.com/microsoft/guidance/assets/26394168/458e0d27-f970-4530-96c2-3f17e75741c2)

Issue 2: Generated content is out of choices.

![image](https://github.com/microsoft/guidance/assets/26394168/ddd7d3c7-4e1c-4699-8627-9a20a9e1c1e9)

As shown in figure above, 'e Yes' is not a valid choice.

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): Linux
 - Guidance Version (`guidance.__version__`): 0.0.63

**Comment by Malet** [comment]
Same issue on 0.0.64, I'm able to replicate using the jsonformer example
![image](https://github.com/microsoft/guidance/assets/358505/4d9d8ac6-36f4-4d15-bfe7-01e3c842a73f)

**Comment by sarthakgarg** [comment]
Facing the same issue, any updates on this bug?

**Comment by marcotcr** [comment]
Sorry it took us so long to get to this. We made _a lot_ of changes [in the new release](https://github.com/guidance-ai/guidance/discussions/429), hopefully select is now working properly!
