### ISSUE TITLE
save state of model and and rerun starting from state

### ISSUE THREAD

**Issue by lbarraga** [guidance-ai/guidance#249]
Hi all,

I was wondering if it is possible to save the state of a model and re-use that that state many times.
I now have a model which i gave many examples (this is davinci). It is very costly to re-run this model each time i want an output.
So, is there any way the state of the model (in which all the examples are loaded) can be saved and reused? I am aware a model can be fine-tuned, but I think saving the state when examples were just given to the model is a bit better.
Apologies if this is not the right place for this question.

best regards

**Comment by slonoed** [comment]
This is something I want to reuse as well. It can help building stateless service with guidance if clients can serialize previous program state.

**Comment by marcotcr** [comment]
This is trivial to do in the [new release](https://github.com/guidance-ai/guidance/discussions/429), where you can save intermediate state in an `lm` object. Sorry it took us so long to get to it :)
