### ISSUE TITLE
#select results in awkward string concatenation of all options

### ISSUE THREAD

**Issue by onlyphantom** [guidance-ai/guidance#256]
**The bug**
As of 0.0.63, the README's `#select` example no longer works. 

**To Reproduce**
Extracted from the readme, the following select block will cause the options to be repeated, resulting in an awkward looking string like `910111210` (9, 10, 11, 12 being concatenated as options, and the extra 10 was the selected option) instead of the highest probability option (eg. `10`)

```python
guidance.llm = guidance.llms.OpenAI("text-davinci-003")
program = guidance(
    """Tweak this proverb to apply to model instructions instead.
 
    Where there is no guidance{{gen 'rewrite' stop="\\n-"}}
    - GPT {{#select 'chapter'}}9{{or}}10{{or}}11{{/select}}:{{gen 'verse'}}
    """
)
```

The workaround of using a non-block, inline version works with a small caveat:

```python
guidance.llm = guidance.llms.OpenAI("text-davinci-003")
chapter_options = ["13", "14", "15"]
program = guidance(
    """Tweak this proverb to apply to model instructions instead.

    {{proverb}}
    - {{book}} {{chapter}}:{{verse}}

    OUTPUT
    - GPT {{select 'chapter' options=chapter_options, logprobs='logprobs'}}"""
)
```
This works but under two conditions:
- without the `logprobs` parameters (logprobs work with the block version, but not the non-block version); 
- set each value in the option list as a string so that string concatenation through the `+` operand works as intended. 

Passing integers as options will raise a `TypeError: unsupported operand type(s) for +: 'int' and 'str'`.

Passing in the `logprobs` to get the log probabilities result in a `SyntaxException: Expected end of text, found '{'`

Changing the model to `gpt-3.5-turbo` did not work as well. Since this is the first example given in the README, I feel we should switch the example to either the non-block version, or introduce regex to further parse / process the string to remove the choice strings.

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): Ubuntu 22.10
 - Guidance Version (`guidance.__version__`): 0.0.63

**Comment by AI-Ahmed** [comment]
That's true, it no longer works!

**Comment by marcotcr** [comment]
Sorry it took us so long to get to this. We made a lot of changes [in the new release](https://github.com/guidance-ai/guidance/discussions/429), hopefully select is now working properly!
