### ISSUE TITLE
C# porting

### ISSUE THREAD

**Issue by MithrilMan** [guidance-ai/guidance#259]
Hello,
reading through your repo I find what you are doing quite interesting.
I'm implementing LLM integration in my own C# opensource project from scratch (I know there is semantic kernel but I've my own ideas I'm pushing forward) and since I wanted to do something similar by using c# template libraries like Fluid (port of Liquid shopify template) I was wondering if maybe you are goint to have a C# implementation of your library too.
I suspect you have several teams at microsoft working on several different LLM related projects and that your project doesn't share anything with semantic kernel, but maybe a porting is in your roadmap?

Thanks

P.S.
Did you ever considered using Liquid template in the building of your project? Do you think that library doesn't implement needed features to generate a "progressive template" like you are doing? In case you aren't porting this to C# I'm going anyway to invest some time into creating something similar to with Fluid/Liquid so would be nice to have some insight from you

thanks

**Comment by boukeversteegh** [comment]
Hi, I was also interested in using Guidance from a C# context, so I've just now published the first version of a C# library for guidance called [Guidance.Net](https://github.com/boukeversteegh/Guidance.Net). It currently features a DSL (work in progress) to generate Guidance scripts that you could execute in python.

Running the guidance programs directly from C# would be even better. My first thought was to rely on [LLamaSharp](https://github.com/SciSharp/LLamaSharp).

By the way, thanks for pointing out Semantic Kernel. That project seems quite in overlap with Guidance. Not sure how the two will co-exist.

**Comment by MithrilMan** [comment]
@boukeversteegh my goal is to have a c# native parser that handle the LLM integration, so it's more complex than having a fluid c# syntax that help building the textual prompt.
Also the pros of these kind of templates is that you can just have a plain text and you are ready to go, so having a syntax in C# isn't actually what I'm looking for.

What would be nice is a C# library that have all the guidance feature that you can customize by injecting into the DI container the interfaces implementations that make the real calls to the LLM

**Comment by marcotcr** [comment]
Hello there. We don't have a c# version, nor do we plan on implementing it (sorry). Hopefully when we implement server - client (soon), it will be trivial to just write a wrapper in C#
