### ISSUE TITLE
Await example in `tutorial.ipynb` does not work as expected

### ISSUE THREAD

**Issue by chc273** [guidance-ai/guidance#260]
**The bug**
In the example, 

```python
# sometimes you want to partially execute a program, the `await` command allows you to do this
# it awaits a variable and then consumes that variables (so after the await command the variable)
prompt = guidance('''Generate a response to the following email:
{{email}}.
Response:{{gen "response"}}
{{await 'instruction'}}
{{gen 'updated_response'}}''', stream=True)

# note how the executed program is only partially executed, it stops at the await command
# because the instruction variable is not yet set
prompt = prompt(email='Hello there')
```
the user is supposed to continue running by supplying `instruction`. However, the `prompt` here is a python generator (`<generator object Program._stream_run at 0x7fee2191d190>`), which cannot run 

```python
----> 1 prompt2 = prompt(instruction='Please translate the response above to Portuguese.')
      2 prompt2

TypeError: 'generator' object is not callable
```

**To Reproduce**
Please see above
```python
please see above
```

**System info (please complete the following information):**
 - OS: MacOS
 - Guidance Version `0.0.63`

**Comment by manasriktam** [comment]
Yes, Facing same issue in this tutorial.

**Comment by zx12671** [comment]
same

**Comment by pluna** [comment]
Same here.
Workaround: change parameter stream to false.

`prompt1 = guidance('''Generate a response to the following email:
{{email}}.
Response:{{gen "response"}}
{{await 'instruction'}}
{{gen 'updated_response'}}''', stream=False)`

**Comment by marcotcr** [comment]
We did away with `await` in the [new release](https://github.com/guidance-ai/guidance/discussions/429), where everything is much simpler by virtue of being pure python. Sorry we took so long to get to this! :)
