### ISSUE TITLE
Address incompatibility with GPT4 more above the fold

### ISSUE THREAD

**Issue by qrdlgit** [guidance-ai/guidance#27]
I'm seeing this popup around twitter.  I've been thinking of workarounds, but perhaps you could highlight the issue as it seems to be pervasive.  I'm also curious what you folks think on how to best address

![image](https://github.com/microsoft/guidance/assets/129564070/4229593e-a5c6-4982-b2a7-07ff517ab99e)

**Comment by marcotcr** [comment]
Hey, sorry we took so long to address this. Hopefully it's now addressed [here](https://github.com/guidance-ai/guidance#vertex-ai). Also, please check [this](https://github.com/guidance-ai/guidance/discussions/429) out :)
