### ISSUE TITLE
Guidance returning strange Value Error

### ISSUE THREAD

**Issue by astein91** [guidance-ai/guidance#270]
I have been running this same code all day, and all of a sudden this afternoon, requests seem to be broken.  

Here is the Python I am running:

create_candidates = guidance('''
{{#system~}}
You are an expert on party and event planning.
Your job is to help me generate (1) a to-do list  and (2) a supply list for planning this party.
Your to-do list should include an approximate date, relative to the event, when I should complete the task.
You should leverage any information you know about the person you are planning the party for.
{{~/system}}

{{#user}}
Given this prompt and context about the user, please tersely list three goals (do not explain them) and then three things you should keep in mind while generating a plan to achieve the user's goal.
Prompt:{{goal}}.
Context about person: {{context}}
Context about desired event: {{planning_context}}
{{/user}}
{{#assistant~}}
{{gen 'goals' temperature=0 max_tokens=300}}
{{~/assistant}}

{{#user}}
Given the above, I would like you to generate five terse birthday event suggestions that the user can pick between.
Example: "A spa day with a homecooked meal", "A surprise party with her closest friends."
{{/user}}
{{#assistant~}}
{{gen 'ideas' temperature=0 max_tokens=300}}
{{~/assistant}}
''')

prompt = create_candidates(
    goal='I am Sarahs boyfriend. help me plan a birthday event for her.',
    ideas = '',
    context = 'Sarah is a 30 year old woman in San Francisco who likes animals',
    await_missing = True,
    planning_context = 'The event is for 2 people, it should cost less than $1000 and it is in San Francisco, CA.'
    )

This is producing this error consistently now:

ValueError: You cannot set text to an empty string. We interpret empty strings as None in requests.You may set {
  "index": 0,
  "delta": {
    "role": "assistant",
    "content": ""
  },
  "finish_reason": null
}.text = None to delete the property

The stack trace looks like this:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 102, in run
    await self.visit(self.parse_tree)
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 437, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 437, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 404, in visit
    command_output = await command_function(*positional_args, **named_args)
  File "/usr/local/lib/python3.10/dist-packages/guidance/library/_assistant.py", line 13, in assistant
    return await role(name="assistant", hidden=hidden, _parser_context=_parser_context)
  File "/usr/local/lib/python3.10/dist-packages/guidance/library/_role.py", line 14, in role
    out = await parser.visit(
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 437, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 437, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 226, in visit
    visited_children = [await self.visit(child, next_node, next_next_node, prev_node, node, parent_node) for child in node.children]
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 226, in <listcomp>
    visited_children = [await self.visit(child, next_node, next_next_node, prev_node, node, parent_node) for child in node.children]
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 437, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 300, in visit
    command_output = await command_function(*positional_args, **named_args)
  File "/usr/local/lib/python3.10/dist-packages/guidance/library/_gen.py", line 155, in gen
    for resp in gen_obj:
  File "/usr/local/lib/python3.10/dist-packages/guidance/llms/_openai.py", line 192, in stream_then_save
    for curr_out in gen:
  File "/usr/local/lib/python3.10/dist-packages/guidance/llms/_openai.py", line 44, in add_text_to_chat_mode_generator
    c['text'] = c['delta']['content']
  File "/usr/local/lib/python3.10/dist-packages/openai/openai_object.py", line 71, in __setitem__
    raise ValueError(
ValueError: You cannot set text to an empty string. We interpret empty strings as None in requests.You may set {
  "index": 0,
  "delta": {
    "role": "assistant",
    "content": ""
  },
  "finish_reason": null
}.text = None to delete the property

The code works until the assistant is called for the first time. System and user messages both seem to work correctly.

**Comment by jackzhouusa** [comment]
I had the same error around the same time. My scripts stopped working in a sudden due to the same error. Is this because OpenAI changed something on their side?

**Comment by roundpanda** [comment]
Same error on my side, seems OpenAI changed their API in some way

**Comment by micksabox** [comment]
Seeing same error.

**Comment by alanxoc3** [comment]
I have the same error when I enable streaming. It started yesterday too. It works fine if I disable streaming.

```python
guidance("", stream=False)
```

**Comment by jackzhouusa** [comment]
upgrading to 0.0.64 will solve the stream issue. But 0.0.64 might have some other issue [https://github.com/microsoft/guidance/issues/278](url)

**Comment by yash161101** [comment]
Upgrading to 0.0.64 also didn't solve this issue. Is there any other way to tackle this?

**Comment by emuwakwe** [comment]
I'm having this issue as well. Why isn;t this fixed?

**Comment by CarhoJohn** [comment]
Same issue here, with guidance==0.0.64 and openai==0.28.0.

**Comment by marcotcr** [comment]
Hopefully this issue does not present itself anymore in the [new release](https://github.com/guidance-ai/guidance/discussions/429). Sorry it took us so long to get to it!
