### ISSUE TITLE
Why handlebars instead of pure Python?

### ISSUE THREAD

**Issue by calclavia** [guidance-ai/guidance#271]
**Is your feature request related to a problem? Please describe.**
It seems like a lot of actions in Guidance are control flows that use a Handlebars template. This requires users of the library to essentially learn a "new templating language" while giving up the benefits of intellisense and type checks when constructing prompt programs.

**Describe the solution you'd like**
Instead of creating a custom templating language, why not just allow actual Python code to be weaved in with strings? This creates maximum flexibility and could reuse patterns that Python devs are experienced with.

An analogy is React JS allows devs to write JS within React components, thus weaving in "rendering" and "logic" into the same block, without needing to learn much of a templating language.

For example, the following guidance program is written as a template:
```py
program = guidance("""
{{~#system~}}
You are a helpful assistant.
{{~function_def get_current_weather}}
{{~/system~}}

{{~#user~}}
Get the current weather in New York City.
{{~/user~}}

{{~#while True~}}
    {{~#assistant~}}
    {{gen 'answer' temperature=1.0 max_tokens=50 functions="auto"}}
    {{~/assistant~}}

    {{#if answer_function_call}}
        {{~#function~}}
        {{answer_function_call()}}
        {{~/function~}}
    {{else}}
        {{break}}
    {{/if}}
{{/while}}
""")
```

But wouldn't it be more Pythonic to just construct some function/generator that looks like this?
```py
@guidance
async def prompt(get_current_weather):
    yield SystemMessage(
        "You are a helpful assistant.",
        func=get_current_weather
    )
    yield UserMessage("Get the current weather in New York City.")

    while True:
        yield AssistantGenerate("answer", temperature=1.0, max_tokens=50, functions="auto")
        if answer_function_call:
            answer_function_call()
        else:
            break
```

^ This is just some pseudo-code, it probably won't work. I'm proposing some alternative ideas and would love to hear some design decisions/ideas/feedback!

**Comment by slundberg** [comment]
@calclavia This is a great question. And there is a lot that could be said here, but perhaps I'll just start by sharing an example of some more pythonic interface code we have been experimenting with and see what you think. There are meaningful tradeoffs here, but there are also some exciting new directions. The code below shows some ideas we have about centering the whole process on updating the state of a language model (LM) object. Guidance programs would then become pure python functions.

In the example below calling the LM will return a new LM object updated to include that new text in its prompt. Dot chaining will sequentially update the state of the model until we have executed everything we want. There is some complexity around getting streaming to work well, but suffice it to say that can be hidden from the user in the example below.

```python
# set the default language model used to execute guidance programs
lm = guidance.llms.OpenAI("text-davinci-003")

# define a guidance program that adapts a proverb
def program(lm, proverb, book, chapter, verse):
    return lm(f"""Tweak this proverb to apply to model instructions instead.

{proverb}
- {book} {chapter}:{verse}

UPDATED
Where there is no guidance""").generate('rewrite', stop="\\n-")("""
- GPT """).select('new_verse', options=[9, 10, 11])(":").generate("new_verse")

executed_lm = program(
    lm=lm,
    proverb="Where there is no guidance, a people falls,\nbut in an abundance of counselors there is safety.",
    book="Proverbs",
    chapter=11,
    verse=14
)

# we can now access named variables on the returned lm object
executed_lm["rewrite"]
```

**Comment by calclavia** [comment]
Initial Thoughts:

So this is sort of a state machine/builder-pattern? You start with an empty state, and you update the state?

It seems like this example chains a bunch of calls, which could make sense. The downside is (maybe due to indentation or my lack of knowledge of what `generate` does) it isn't apparent to me what the control flow looks like now. Does generate return a new function - it seems like it's a higher-order function because it returns a callable?

What if my subsequent chained call requires a different parameterization, or uses a different model? Could I chain a GPT-3.5 call with a GPT-4 call? Just thinking about use cases...

**Comment by slundberg** [comment]
Every step returns a new lm object, so we could rewrite the program above without dot-chaining like this:
```python
def program(lm, proverb, book, chapter, verse):
    lm = lm(f"""Tweak this proverb to apply to model instructions instead.

{proverb}
- {book} {chapter}:{verse}

UPDATED
Where there is no guidance""")
    lm = lm.generate('rewrite', stop="\\n-")
    lm = lm("""\n- GPT """)
    lm = lm.select('new_chapter', options=["9", "10", "11"])
    lm = lm(":")
    lm = lm.generate("new_verse")

    return lm
```

As for switching different LMs, it is important to keep in mind that guidance acceleration works by incrementally building up the state of an LM, so switching LMs would force you to rebuild all that state from scratch (you can't switch LMs in a guidance program right now, you need two programs). But in this syntax it would not be too hard to switch LMs, you just need to copy the state from one LMs to another and then continuing building from there:

```python
lm = guidance.lms.OpenAI("text-davinci-003")
lm2 = guidance.lms.OpenAI("text-curie-001")

def program_2lms(lm, lm2, proverb, book, chapter, verse):
    lm = lm(f"""Tweak this proverb to apply to model instructions instead.

{proverb}
- {book} {chapter}:{verse}

UPDATED
Where there is no guidance""")
    lm = lm.generate('rewrite', stop="\\n-")
    lm = lm("""\n- GPT """)
    lm = lm.select('new_chapter', options=["9", "10", "11"])
    lm = lm(":")
    
    lm2 = lm2(lm)
    lm2 = lm2.generate("new_verse")

    return lm2
```

As for changing parameterizations those are all just arguments to the generate function right now (and the lm objects also have default I suppose we could allow to be updated)

**Comment by calclavia** [comment]
This looks promising.

Maybe the object chained shouldn't be called an `lm`, but something like `lm_state`? It seems like every time a program starts, it initializes with an initial LM state, which is then "built" through several instructions.

Also, using calling `lm("\n- GPT ")` is a bit confusing. A named function like `lm.append("\n- GPT ")` would be clearer on what it does.

**Comment by slundberg** [comment]
@calclavia everything is pure python in our experimental setup, so control flow statements are just python code.

- the name `lm` is because you really can think of these objects as the underlying model. Every time we update the model we get a new model object in a new state. All the objects we get in a single pythonic guidance program can share a common backend session object for performance reasons, but logically we can think of them as independent LMs.
- still playing with calling syntax, for now we have call and `__add__`. I think "calling" a language model with a prompt makes sense, but I might be odd there. (I don't want to use `append` since that implies inplace modification)
- If it works it means a lot of changes so we are working hard to sort out if there are any show stoppers. So far everything is looking really good. For example block level elements are now `with` blocks:
<img width="994" alt="image" src="https://github.com/microsoft/guidance/assets/3740613/6da714ec-69b5-4d0e-ad9e-5500360d248c">
- We also have streaming and async support working with dot chains

thanks again for the continuing feedback :)

**Comment by calclavia** [comment]
When you call a language model, my assumption is you're sending an API call to OpenAI. It seems like most other frameworks refer to calling a model as generating - might be confusing. 

Whereas appending or adding to the current prompt buffer makes more sense?

**Comment by PiotrCzapla** [comment]
It will be tricky to get the next token to fill the stop in gen though. How would the syntax to fill out the blanks in json look like?  Current approach with handlebars is awesome to read.

**Comment by marcotcr** [comment]
We have a [new release](https://github.com/guidance-ai/guidance/discussions/429) that started with this thread, thank you :)

Hopefully f-strings are still readable enough even with json examples, and _everything_ else is _way_ better :)
