### ISSUE TITLE
SSL connection issue with latest version of guidance and openai

### ISSUE THREAD

**Issue by davoice-321** [guidance-ai/guidance#276]
**The bug**
Latest version of guidance appears to cause openai ssl connection errors. 

**To Reproduce**
Basic loading of guidance program. No special code used other than what is in the documentation. 

However, the problem appeared when using guidance 0.0.64 and openai  0.27.8

Here is the error message:

raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.openai.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')] 

Note: Downgrading to openai 0.27.7 and guidance 0.0.60 resolved the error. 

**System info:**
 - OS (Linux ): Kernel: Linux 3.10.0-962.3.2.lve1.5.56.el7.x86_64
 - Guidance Version (`guidance.0.0.64`):

**Comment by CarhoJohn** [comment]
> Note: Downgrading to openai 0.27.7 and guidance 0.0.60 resolved the error.

I have the same problem. After downgrading these packages, it works well. Thanks!

**Comment by marcotcr** [comment]
Hopefully this is fixed in the [new release](https://github.com/guidance-ai/guidance/discussions/429). Sorry it took us so long to get to it!
