### ISSUE TITLE
Not enough values to unpack (select followed by gen)

### ISSUE THREAD

**Issue by jloganolson** [guidance-ai/guidance#277]
I'm frequently getting an error when using this prompt with a `#select` shortly followed by a `gen`:
```
{{#user~}}
{{query}}
{{~/user}}
{{#assistant~}}
{{#select 'answer'}}Yes{{or}}No{{/select}}

Explanation: {{gen 'explanation'}}
{{~/assistant}}
```

I presume the error `not enough values to unpack (expected 2, got 1)` is due to the generation not reaching 'explanation' - any tips? Insights? Debug strategies? Or ways to mitigate beyond try/except? It happens in about 20% of calls.

**Comment by jloganolson** [comment]
Oh also, if helpful the guidance.llm is starchat:
```python
class StarchatModel(guidance.llms.Transformers):
    def __init__(self, model_path, **kwargs):
        tokenizer = AutoTokenizer.from_pretrained(
            model_path, device_map='auto')
        model = AutoModelForCausalLM.from_pretrained(
            model_path, device_map='auto', load_in_4bit=True, use_cache=True)
        super().__init__(model, tokenizer=tokenizer, device_map='auto', **kwargs)

    @staticmethod
    def role_start(role):
        return "<|"+role+"|>"

    @staticmethod
    def role_end(role):
        return '<|end|>'

guidance.llm = StarcoderChat(model_path)
```

**Comment by marcotcr** [comment]
Hopefully this is fixed in the [new release](https://github.com/guidance-ai/guidance/discussions/429). Sorry it took us so long to get to it!
