### ISSUE TITLE
await can't get the input

### ISSUE THREAD

**Issue by jackzhouusa** [guidance-ai/guidance#278]
- OS: Mac OS
 - Guidance Version: 0.0.64

```python
import os
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

import guidance
chatgpt = guidance.llms.OpenAI("gpt-4")

terminal = guidance('''
    {{#system~}}
        You are a helpful assistant.
    {{~/system}}

    {{#user~}}
        Please answer this question: do you like SF or LA?
    {{~/user}}

    {{#geneach 'responses'}}
        {{#assistant~}}
            {{gen 'this.response' temperature=0.7 max_tokens=256 stop="Observation:"}}
        {{~/assistant}}

        {{#assistant~}}
            Observation: {{set 'this.observation' (await 'observation')}}
        {{/assistant}}
    {{/geneach}}
''')

t = terminal(llm = chatgpt)

t = t(observation = "SF is cooler.")
```
Output:
<img width="2202" alt="image" src="https://github.com/microsoft/guidance/assets/16514078/63b869b5-7cbf-452b-8374-5d5605c0ea99">

**Comment by bllchmbrs** [comment]
What's the priority of this bug from the developers? Is this a critical issue?

**Comment by magick93** [comment]
Yes, this is a blocker for me too

**Comment by ruidongtd** [comment]
me too

**Comment by rickbraddy-pharma** [comment]
Us too

**Comment by lwarne** [comment]
Per this test https://github.com/microsoft/guidance/blob/0.0.64/tests/library/test_await.py, use` hidden=False` in the await command

{{set 'user_response' (await 'user_response') hidden=False}}

**Comment by webstruck** [comment]
> Per this test https://github.com/microsoft/guidance/blob/0.0.64/tests/library/test_await.py, use` hidden=False` in the set/await command
> 
> `{{set 'user_response' (await 'user_response') hidden=False}}`

This looks like a workaround for now.

**Comment by Ridealist** [comment]
> Per this test https://github.com/microsoft/guidance/blob/0.0.64/tests/library/test_await.py, use` hidden=False` in the set/await command
> 
> `{{set 'user_response' (await 'user_response') hidden=False}}`

Thanks a lot:) I've been almost 2 hours finding out what am I wrong...

**Comment by marcotcr** [comment]
We did away with `await` in the [new release](https://github.com/guidance-ai/guidance/discussions/429), where everything is much simpler by virtue of being pure python. Sorry we took so long to get to this! :)
