### ISSUE TITLE
JSON Output Example Gives Extra Answers

### ISSUE THREAD

**Issue by qianz-z** [guidance-ai/guidance#285]
**The bug**
The program produces extra answers even though not specified. Also, the program does not follow the keys that I have specified.

**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.
```python
guidance.llm = guidance.llms.transformers.Vicuna("eachadea/vicuna-7b-1.1")
os = ["windows", "linux", "mac"]

# define the prompt
program = guidance("""Generate a character profile for each intern in JSON format.
```json
{
    "name": "{{name}}",
    "strengths": {{gen 'strengths'}},
    "weaknesses": {{gen 'weaknesses'}},
    "likes": {{gen 'likes'}},
    "dislikes": {{gen 'dislikes'}},
    "favourite operating system": "{{select 'fav_os' options=os}}",
    "favourite food": [{{#geneach 'food' num_iterations=3}}
        "{{gen 'this'}}",{{/geneach}}],
}```""")
sy = program(name = "sy", os=os)
```

Results:
![image](https://github.com/microsoft/guidance/assets/85693125/ccdc6984-2816-4ec9-97ad-1b3fa47b32c8)
![image](https://github.com/microsoft/guidance/assets/85693125/22e4bf99-add2-4b33-b48e-131931343f71)

**System info (please complete the following information):**
 - OS (Ubuntu)
 - Guidance Version (`guidance.__version__`): tried 0.0.61 and 0.0.63, both has the same issue

**Comment by aniquetahir** [comment]
change `"strengths": {{gen 'strengths'}},` to `"strengths": {{gen 'strengths' stop=","}},`

**Comment by tensiondriven** [comment]
@aniquetahir Can you explain why `{{gen 'strengths' stop=","}}` would prevent the outer structure from being repeated?  As I read that, it suggests that it should generate a single strength in an array (which would be the same as `num_iterations=3`, i imagine)

I image its early and there aren't formal docs, but if there were, I'd love to read 'em.  (I checked the README and https://guidance.readthedocs.io/en/latest/api.html , which mention 'stop' but don't provide a description of what it does that fits with your suggestion.)

**Comment by aniquetahir** [comment]
Right. I overlooked that its an array.
`"strengths": [{{gen 'strengths' stop="],"}}],` might work. Basically the problem with the original generation is that it doesn't know when to stop so it produces the rest of the json.

**Comment by alexb1200** [comment]
Guidance version 0.0.57 and previous stops correctly. Those versions seemed to use the given prompt's next tokens after the gen call to determine stop tokens.

**Comment by marcotcr** [comment]
@alexb1200 explained it correctly. We'll add some helper for valid json to the [new release](https://github.com/guidance-ai/guidance/discussions/429), hopefully soon.
