### ISSUE TITLE
Does Guidance with chat-based models have chat history feature?

### ISSUE THREAD

**Issue by qianz-z** [guidance-ai/guidance#286]
**Is your feature request related to a problem? Please describe.** No
So that users can refer back to the previous response generated by the large language model.

**Describe the solution you'd like**
Chat history feature
{{chat_history}} in the prompt

I am unable to find such feature in the current version. Would be great if someone can point me to the right page if I overlooked it!

**Comment by tensiondriven** [comment]
No, i don't think so.  That would be out of scope for what the project is trying to do.

Saving the chat is an exercise left for the application developer.

**Comment by marcotcr** [comment]
Very easy to do in the [new release](https://github.com/guidance-ai/guidance/discussions/429) :)
