### ISSUE TITLE
select options - RuntimeWarning: divide by zero encountered in log

### ISSUE THREAD

**Issue by albernar** [guidance-ai/guidance#287]
**The bug**
When using the select option specifying a list of options with 3+ elements in which two have a very similar encoding, at line 146 of guidance/select/_select.py, computing the logarithm of zero raises an error.

**To Reproduce**
transformers.__version__ == 4.29.2
guidance.__version__ == 0.0.64
```python
from transformers import AutoTokenizer, AutoModelForCausalLM
import guidance

def main():
    tokenizer = AutoTokenizer.from_pretrained('gpt2')
    model = AutoModelForCausalLM.from_pretrained('gpt2')

    gpt2 = guidance.llms.Transformers(model=model, tokenizer=tokenizer)
    guidance.llm = gpt2

    valid_options = ["HTR2C", "NR3C1", "HTR2A"]
    program = guidance("""The best option is: {{select 'acronyms' options=valid_options}}""")
    executed_program = program(valid_options=valid_options)


if __name__ == '__main__':
    main()
```

```
PYTHON_PATH/site-packages/guidance/library/_select.py:146: RuntimeWarning: divide by zero encountered in log
  logprobs_out[k] = np.log(or_prob)
```

**System info (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - Guidance Version: 0.0.64

**Additional Notes**

Trying to debug the issue I have noticed a couple of things, I hope they can help:
- The warning is not raised if the list of valid_options is ["HTR2C", "HTR2A”], i.e., if the list is made up of only the elements with similar encodings, though these are the problem (see next point)
- The issue is caused by `sub_logprobs`, which after the recursive call of recursive_select is defined as 

```python
{ (464, 1266, 3038, 318, 25, 367, 5446, 17, 34, 50256): -1000, 
(464, 1266, 3038, 318, 25, 367, 5446, 17, 32, 50256): -0.4258567988872528 }
```

I believe the bug lies in the fact that the first element of the above dictionary should not be there as the token 32 was selected as the best for prefix=[464, 1266, 3038, 318, 25, 367, 5446, 17], so that the other option should have been discarded. However, I couldn’t understand why that first element appears in sub_logprobs (maybe is an effect of async?)

**Comment by joshuaipwork** [comment]
I'm also having this problem with the sample program shown on the readme page.

**Comment by marcotcr** [comment]
Hopefully this is fixed in the [new release](https://github.com/guidance-ai/guidance/discussions/429), where we fixed a ton of select bugs. Sorry it took us so long to get to it!
