### ISSUE TITLE
Regression in output capture of partials in commit 00061250ac42faae6ad4df246f383b3404d7bce0

### ISSUE THREAD

**Issue by jonathanasdf** [guidance-ai/guidance#296]
```
import guidance
from ..utils import get_llm

def test_partial_capture():
    partial = 'Test {{#block}}example{{/block}}'
    prompt = guidance('This is a {{>partial}}')
    out = prompt(partial=guidance(partial))
    assert out.text == 'This is a Test example'
    assert out['partial'] == 'Test example'
```

This test works before that commit (d9d0ab193b50f3df7f419d8c5d6f49d5664cd19b) and fails at that commit (00061250ac42faae6ad4df246f383b3404d7bce0)

**Comment by marcotcr** [comment]
Hopefully this is fixed in the [new release](https://github.com/guidance-ai/guidance/discussions/429). Sorry it took us so long to get to it!
