### ISSUE TITLE
When use "elif", the "else" block won't be triggered whatever the flag of 'elif' is True or False.

### ISSUE THREAD

**Issue by XLzed** [guidance-ai/guidance#297]
**The bug**
When use "elif", the "else" block won't be triggered whatever the flag of 'elif' is True or False.

**To Reproduce**
Failed to execute the following program.
```python
def test_elif_else():
    """ Test the behavior of `if` with an `else` clause.
    """
    prompt = guidance("""Answer 'Yes' or 'No': '{{#if flag}}Yes{{elif flag2}}maybe{{else}}No{{/if}}'""")

    out = prompt(flag=False, flag2=False)
    assert str(out) == "Answer 'Yes' or 'No': 'No'"
```

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): CentOS Linux 7
 - Guidance Version (`guidance.__version__`): 0.0.64

**Comment by xnohat** [comment]
`

        # elif block
        if block_content[i][0] == "elif":
            if parser.visit(block_content[i][1], variable_stack):
                return await parser.visit(block_content[i+1], variable_stack)

        # else block
        elif block_content[i][0] == "else":
            return await parser.visit(block_content[i+1], variable_stack)`

Code of IF block , at part of elif . There are no condition check ?!?!?

**Comment by xnohat** [comment]
I proposed a fix for {{elif}} statement https://github.com/guidance-ai/guidance/pull/351

**Comment by marcotcr** [comment]
We did away with handlebars in the [new release](https://github.com/guidance-ai/guidance/discussions/429). Hopefully pure python makes everything cleaner :)
