### ISSUE TITLE
Add parameter to skip generation.

### ISSUE THREAD

**Issue by simon-lund** [guidance-ai/guidance#300]
**Is your feature request related to a problem? Please describe.**
I want to view the generated template with all provided inputs but skip the gen fields/contents.
This would be nice for testing inputs and reviewing the resulting format of the prompt.

**Describe the solution you'd like**
A possible solution could be a `skipgen` parameter, which defaults to False but could be set to True to skip all gen commands.

**Additional context**
This will throw an error, unless you remove the gen field.
Instead, it would be nice if one was able to add `skipgen` when calling the program

```python
import guidance

program = guidance("{{question}} {{gen 'answer'}}", )
x = program(question="Is America a country?")

print(x)
```

**Comment by marcotcr** [comment]
We changed a lot of what gets displayed in the [new release](https://github.com/guidance-ai/guidance/discussions/429). Please check it out :)
