### ISSUE TITLE
ServiceUnavailableError not propagated to caller code

### ISSUE THREAD

**Issue by markmacau** [guidance-ai/guidance#308]
**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to error handling within the Guidance library. Currently, certain errors from the underlying OpenAI API (e.g., ServiceUnavailableError) do not propagate to the code that calls the Guidance functions. This hampers the ability to handle such errors appropriately, leading to potentially unexpected behavior in applications that use Guidance.

While running a task using the Guidance module in an AWS Lambda function, I've encountered a ServiceUnavailableError from the OpenAI API. This error is seen in the CloudWatch logs, but it doesn't seem to propagate to the caller code where I have an Exception handling block.

Here's a snippet of my code:
```python
try:
    guidanceResult = experts(stream=False, silent=True)
    # other code...
except Exception as e:
    print("An error occurred while calling the experts function: ", e)
    res["error"]=e
    raise
```

**Describe the solution you'd like**
I'd like the Guidance library to propagate all exceptions raised by the underlying OpenAI API to the calling code. 

**Describe alternatives you've considered**
An alternative would be to provide a configuration option in the Guidance library to determine how it should handle certain errors.

**Comment by zwhe99** [comment]
I'm having the same problem.

**Comment by marcotcr** [comment]
Hopefully this is fixed in the [new release](https://github.com/guidance-ai/guidance/discussions/429). Sorry it took us so long to get to it!
