### ISSUE TITLE
Pattern controls fail silently with guidance 0.0.64

### ISSUE THREAD

**Issue by hudson-ai** [guidance-ai/guidance#311]
Attempting to use pattern controls with an OpenAI LLM fails silently with guidance version `0.0.64`, where `0.0.63` and earlier raise assertion errors.

**To Reproduce**
```python
import guidance
import re

# set the default language model used to execute guidance programs
llm = guidance.llms.OpenAI("text-davinci-003")

character_maker = guidance("""The following is a character profile for an RPG game in JSON format.
```json
{
    "name": "{{gen 'name' stop=','}}",
    "age": {{gen 'age' pattern='[0-9]+' stop=','}},

}```""")

out = character_maker(llm=llm)
```

**System info (please complete the following information):**
 - OS: Ubunbtu
 - Guidance Version `0.0.64`

**Comment by PNAKTEMPORAL** [comment]
+1. Guidance outputs an unchanged template text and doesn't throw any errors. LLM could be a guidance.llms.Transformers and yet show the same behavior.
Easiest repro - notebook https://github.com/microsoft/guidance/blob/main/notebooks/guaranteeing_valid_syntax.ipynb
@slundberg @marcotcr

**Comment by VikParuchuri** [comment]
You can try looking at the `_exception` property of `character_maker` - if there is an exception when running, it may be stored there, but not surfaced for some reason.

**Comment by anatoliykmetyuk** [comment]
> You can try looking at the `_exception` property of `character_maker` - if there is an exception when running, it may be stored there, but not surfaced for some reason.

This helped me sort out my problem: turns out you can't generate inside GPT-3.5 model without using roles... I feel like this `_exception` property should be documented, inside the Jupyter notebook you don't see many exceptions!

**Comment by AI-Ahmed** [comment]
There is a problem with this package after the last release. The errors don't raise as previously.

**Comment by benwhalley** [comment]
The fact that exceptions are hidden is a real pain... is there a reason to hide them?

**Comment by marcotcr** [comment]
Hopefully this is fixed in the [new release](https://github.com/guidance-ai/guidance/discussions/429). Pattern (now called ` Sorry it took us so long to get to it!
