### ISSUE TITLE
Command to select from a set of options does not work

### ISSUE THREAD

**Issue by Roberto7766** [guidance-ai/guidance#323]
I'm replicating the tutorial (https://github.com/microsoft/guidance/blob/main/notebooks/tutorial.ipynb) commands in colab.

When I try the code:
_# the {{#select}} command allows you to use the LLM to select from a set of options
program = guidance('''Is the following sentence offensive? Please answer with a single word, either "Yes", "No", or "Maybe".
Sentence: {{example}}
Answer:{{#select "answer" logprobs='logprobs'}} Yes{{or}} No{{or}} Maybe{{/select}}''')
executed_program = program(example='I hate tacos')_

I obtain multiple answers instead of only one:
_Is the following sentence offensive? Please answer with a single word, either "Yes", "No", or "Maybe".
Sentence: I hate tacos
Answer: **Yes No Maybe Maybe**_

Am I doing something wrong?

**Comment by Wirg** [comment]
Seems to be related to : https://github.com/microsoft/guidance/issues/248#issuecomment-1616158391 .

I think there is a bug. It may be only `program.text`and the real value of `answer` might be ok. It was the case for me but apparently not fully right in the issue's comment.
Currently, I am using the other syntax that seems to work better. 
`Answer:{{select "answer" logprobs='logprobs' valud}} options=["Yes", "No", "Maybe"]}}`

**Comment by marcotcr** [comment]
Hopefully this is fixed in the [new release](https://github.com/guidance-ai/guidance/discussions/429), where we fixed a lot of select bugs. Sorry it took us so long to get to it!
