### ISSUE TITLE
If statement within Guidance does not seem working

### ISSUE THREAD

**Issue by skprasadu** [guidance-ai/guidance#325]
**The bug**
In the "Using tools" section in the tutorial.ipynb, For the below code it is throwing an error.

**To Reproduce**
Load the tutorial.ipynb file in Jupyter and running the block, 

```python
{{#each practice}}
{{#if (== this.role "user")}}
{{#user}}{{this.content}}{{/user}}
{{else}}
{{#assistant}}{{this.content}}{{/assistant}}
{{/if}}
{{/each}}
```

it is giving, 

```python


File ~\AppData\Roaming\Python\Python311\site-packages\guidance\_program_executor.py:64, in ProgramExecutor.__init__(self, program)
     61 msg += program._text[e.loc:e.loc+40] + "\n"
     62 msg += " " * len(initial_str) + "^\n"
---> 64 raise SyntaxException(msg, e) from None

SyntaxException: , found '='  (at char 398), (line:15, col:8)

{{#if (== this.role "user")}}{{#user}}{{this.co
       ^
```

Any help will be appreciated.

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.):
 - Guidance Version (`guidance.__version__`):

**Comment by marcotcr** [comment]
We did away with handlebars in the [new release](https://github.com/guidance-ai/guidance/discussions/429), where if statements are now pure python (and _will_ work) :)
Sorry it took us so long to get to this
