### ISSUE TITLE
codellama support?

### ISSUE THREAD

**Issue by johndpope** [guidance-ai/guidance#328]
is this possible? or have to redo training? or ?

**Comment by smellslikeml** [comment]
It does! We've tested on a custom fine-tuned llama2-7b model (remyxai/ffmperative-7b hosted on huggingface). Both models (llama 1 & 2) use the same HF code.

`guidance.llm = guidance.llms.transformers.LLaMA("remyxai/ffmperative-7b", device_map="auto")`

**Comment by johndpope** [comment]
https://github.com/QuangBK/localLLM_guidance

**Comment by danikhan632** [comment]
Let me try updating, unsure if repo is still active

**Comment by VarunGumma** [comment]
Any update on using `LLama2` chat models with `guidance` ??

**Comment by danikhan632** [comment]
expect something maybe friday

**Comment by johndpope** [comment]
it looks like @iiis-ai has a working example with llama 1 / maybe working with llama2?

https://github.com/iiis-ai/cumulative-reasoning/blob/6c8632577699a8b3f8eee88671ee83c677fa4aea/AutoTNLI/autotnli-direct.py#L22

guidance.llm = guidance.llms.transformers.LLaMA(args.model, device_map="auto", token_healing=True, torch_dtype=torch.bfloat16)
https://github.com/yifanzhang-pro/cumulative-reasoning-anonymous/blob/07bcc6b21aedbee7c82f44b52aa3c0fc123e4d03/AutoTNLI/autotnli-cr.py#L27

**Comment by marcotcr** [comment]
LLama2 works fine in the [new release](https://github.com/guidance-ai/guidance/discussions/429), both with HF transformers and with llama.cpp. Please check [this](https://github.com/guidance-ai/guidance#loading-models) out
