### ISSUE TITLE
`select` function contains error when options share a prefix

### ISSUE THREAD

**Issue by rhelmeczi** [guidance-ai/guidance#338]
**The bug**
The `select` function does not execute when the options share a prefix.

**To Reproduce**

Here is the shared setup:

```python
import guidance

api_key = ... # openai api key

guidance.llm = guidance.llms.OpenAI(
    "gpt-3.5-turbo", api_key=api_key
)

prompt = guidance(
    """
{{#system~}}
You are a helpful and terse assistant.
{{~/system}}

{{#user~}}
{{message}}
{{~/user}}

{{#assistant~}}
{{select 'response' options=response_options}}
{{~/assistant}}
"""
)
```

The following will not work:

```python
response =prompt(
    message="Hello",
    response_options=[
        "This message contains a greeting.",
        "This message contains financial terminology."
    ]
)
```

it returns

```
{{#system~}}
You are a helpful and terse assistant.
{{~/system}}

{{#user~}}
{{message}}
{{~/user}}

{{#assistant~}}
{{select 'response' options=response_options}}
{{~/assistant}}
```

However, this works fine:

```python
response =prompt(
    message="Hello",
    response_options=[
        "This message contains a greeting.",
        "There is financial terminology in this message."
    ]
)
```

As with GPT acceleration does not work, I cannot integrate the common prefix into the prompt via:

```
{{#assistant~}}
This message contains {{select 'response' options=response_options}}
{{~/assistant}}
```

Presumably, this is a bug with the [common prefix acquisition](https://github.com/microsoft/guidance/blob/a8c9b2b5155f315257a53867aa54b8d60893fde2/guidance/library/_select.py#L83).

While this can be worked around by simply using different prefixes, I think that at the very least the code should throw an error indicating that this is a known problem. As of right now there is no error, just the prompt is returned.

**System info (please complete the following information):**
 - Windows 11
 - python = 3.10.6
 - guidance==0.0.64

**Comment by marcotcr** [comment]
Hopefully this is fixed in the [new release](https://github.com/guidance-ai/guidance/discussions/429), where we fixed a ton of `select` bugs. Sorry it took us so long to get to it!
