### ISSUE TITLE
AttributeError: module 'guidance' has no attribute 'llms'

### ISSUE THREAD

**Issue by YujiaHu0819** [guidance-ai/guidance#346]
**The bug**
I cannot use the llms attribute after I installed the module by 'pip install guidance'. The specific error as follows. Do anybody have good suggestion on this? Thank you in advance.

AttributeError: module 'guidance' has no attribute 'llms'

**To Reproduce**
`
>>> import guidance
>>> gpt4 = guidance.llms.OpenAI("gpt-4")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'guidance' has no attribute 'llms'`

**Comment by WillianXu117** [comment]
same problem too
