### ISSUE TITLE
Data Formatting for Fine-Tuning with Guidance Layer Integration

### ISSUE THREAD

**Issue by BedirT** [guidance-ai/guidance#352]
We are in the process of fine-tuning the LLaMa 2 model using our data. However, our task differs from the conventional instruction-tuning questions. Instead of the straightforward Q-A input-output format typically used in instruction tuning, our model is designed to produce formatted JSON outputs.

Initially, we tried using GPT for this task, employing function calls to generate the desired JSON output. While this approach yielded some success, it was not entirely effective. Moreover, it proved to be inefficient and unnecessarily costly as we found ourselves repetitively using tokens without any significant purpose.

Subsequently, we transitioned to the Guidance method. This change addressed our output concerns, providing a more structured result. The remaining challenge is the quality of the generated output, prompting us to consider fine-tuning an open-source model.

My primary question is about data formatting for fine-tuning when integrating Guidance as a supplementary layer with the fine-tuned model. Should the Q-A data structure mirror the format we intend to implement with Guidance? And if so, how are these two entities related?

**Comment by emrekiciman** [comment]
Hi @BedirT , I think it would be better to fine-tune in a Q-A format that mirrors the format that Guidance will be enforcing.

**Comment by marcotcr** [comment]
What @emrekiciman said, but of course you are free to change the structure you use in guidance (it should be quite easy to do). BTW, please check out our [new release](https://github.com/guidance-ai/guidance/discussions/429), in particular the [chat interface](https://github.com/guidance-ai/guidance#example-changing-intermediate-step-of-a-chat-session), which is very easy to customize if you have your own special tokens / chat formet.
