### ISSUE TITLE
Guidance program silently fails (returns template) if LLM isn't provided with an api_key

### ISSUE THREAD

**Issue by SamMakesThings** [guidance-ai/guidance#353]
**The bug**
As title says, the Guidance program silently fails (returns template) if LLM isn't provided with an api_key. Tested with OpenAI specifically. Just returns the prompt template by default.

**To Reproduce**
Try running the tutorial notebook(s). I ran in colab.

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): Mac OS, but Colab specifically
 - Guidance Version (`guidance.__version__`): 0.0.64

Also - is Guidance still maintained? Pip package hasn't been updated since June.

**Comment by tlongatalaya** [comment]
Also having this issue

**Comment by SamMakesThings** [comment]
This also seems to happen if the API key is hitting a cap 😢 

So it seems no error messages are being passed through.

**Comment by Harsha-Nori** [comment]
Sam, thanks for reporting this. Do you mind checking the `program._exception` property (after executing your guidance program) and letting me know if it gets appropriately logged there? We should be surfacing this.

**Comment by SamMakesThings** [comment]
@Harsha-Nori Yep, that shows the correct error! It's just not getting surfaced in the colab notebook for some reason. Makes for a frustrating onboarding experience

**Comment by Harsha-Nori** [comment]
Thanks for getting back so quickly! Do you mind running your script in a local jupyter notebook/python file and see if the exception still occurs? I'm guessing the exception propagation issues might be specific to colab/cloud notebook environments.  Appreciate you reporting this, and sorry about the frustrating onboard!

**Comment by Thangbeo909** [comment]
I got the same issue as the notebook produce the template as ouput. So confuse, Im on windows 11

**Comment by MohammedYaseenZevi** [comment]
@wzwz180 i saw in an other issue .. it works only if you pass the api key in the following syntax:

```
import openai
openai.api_key=your_api_key
```

**Comment by e3oroush** [comment]
As I understood, this bug (or feature?) is only the case when you run your example on a Notebook. It means, if you run it in a simple Python script you will see the correct exception and logs.  
Can anyone help me and guide me to the right function for updating Notebook output when an exception occurs? @Harsha-Nori

**Comment by marcotcr** [comment]
Hopefully this is fixed in the [new release](https://github.com/guidance-ai/guidance/discussions/429), where error handling is now much more transparent. Sorry it took us so long to get to it!

**Comment by slundberg** [comment]
> Hopefully this is fixed in the [new release](https://github.com/guidance-ai/guidance/discussions/429), where error handling is now much more transparent. Sorry it took us so long to get to it!

We now have much better debugging since guidance functions are python code, so you can step into things and error should get thrown like normal. If you run into any similar issues though please open an issue again!
