### ISSUE TITLE
Better explain guidance acceleration

### ISSUE THREAD

**Issue by kripper** [guidance-ai/guidance#363]
Please explain more in detail you guidance acceleration implementation.

Suggestions:
- include in the documentation some actual internal generated prompts passed to the LLM engine, to better explain what's going on under the hood
- what key/values are being cached?
- is the speed up because the inference process is stopped or because KV cache, or both?
- more insights about the documented benchmark

Thanks

**Comment by marcotcr** [comment]
Hopefully [this](https://github.com/guidance-ai/guidance#fast) explains it _a little_ better :).
