### ISSUE TITLE
Provide generation arguments programatically?

### ISSUE THREAD

**Issue by JohnGiorgi** [guidance-ai/guidance#369]
Is there a way to provide generation arguments to a prompt? E.g. something like

```python
prompt = """
Write me a poem

{{#assistant~}}
{{gen 'output' temperature={{temperature}} max_tokens={{max_tokens}}}}
{{~/assistant}}
"""

response = prompt(temperature=0.2, max_tokens=128)
```

Does this ability exist? Apologies if I am missing it in the documentation but I don't see it.

**Comment by marcotcr** [comment]
This is now much more clear in the [new release](https://github.com/guidance-ai/guidance/discussions/429), where you can literally call `gen(temperature=0.2, max_tokens=128)`
