### ISSUE TITLE
Temperature sampling issue with LLama2 while using guidance

### ISSUE THREAD

**Issue by VarunGumma** [guidance-ai/guidance#375]
**The bug**
I have been trying to use `Llama2` with `guidance` and I do not want to perform temperature sampling, and when I set temperature=0, I get the following error:

`ValueError: temperature (=0.0) has to be a strictly positive float, otherwise your next token scores will be invalid. If you're looking for greedy decoding strategies, set do_sample=False.`

I am not sure how to proceed with this, as `do_sample` is not a recognized command for `gen`, and even setting temperature as a small value like `1e-6` still thowrs the same error.

**To Reproduce**
```python

import guidance

guidance.llm = guidance.llms.transformers.LLaMA(
    "meta-llama/Llama-2-7b-chat-hf",
    device_map="auto",
    low_cpu_mem_usage=True
)

examples = [
    {'input': 'I wrote about shakespeare',
    'entities': [{'entity': 'I', 'time': 'present'}, {'entity': 'Shakespeare', 'time': '16th century'}],
    'reasoning': 'I can write about Shakespeare because he lived in the past with respect to me.',
    'answer': 'No'},
    {'input': 'Shakespeare wrote about me',
    'entities': [{'entity': 'Shakespeare', 'time': '16th century'}, {'entity': 'I', 'time': 'present'}],
    'reasoning': 'Shakespeare cannot have written about me, because he died before I was born',
    'answer': 'Yes'}
]

# define the guidance program
structure_prompt = guidance(
'''Given a sentence tell me whether it contains an anachronism (i.e. whether it could have happened or not based on the time periods associated with the entities).
----

{{~! display the few-shot examples ~}}
{{~#each examples}}
Sentence: {{this.input}}
Entities and dates:{{#each this.entities}}
{{this.entity}}: {{this.time}}{{/each}}
Reasoning: {{this.reasoning}}
Anachronism: {{this.answer}}
---
{{~/each}}

{{~! place the real question at the end }}
Sentence: {{input}}
Entities and dates:
{{gen "entities" temperature=0.000001}}
Reasoning:{{gen "reasoning"}}
Anachronism:{{#select "answer"}} Yes{{or}} No{{/select}}''')

# execute the program
structure_prompt(
    examples=examples,
    input='The T-rex bit my dog'
)
```

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): `Ubuntu 20.04`
 - Guidance Version (`guidance.__version__`): `0.0.64`

**Comment by havocy28** [comment]
this issue seems to be duplicated here with a workaround: https://github.com/guidance-ai/guidance/issues/355

**Comment by marcotcr** [comment]
This is fixed in the [new release](https://github.com/guidance-ai/guidance/discussions/429). Sorry it took us so long to get to it!
