### ISSUE TITLE
{{select}} function doesn't work as expected with LLaMA

### ISSUE THREAD

**Issue by niklub** [guidance-ai/guidance#381]
**The bug**
`{{select}}` doesn't work as expected with Transformers.LLaMA

**To Reproduce**
This doesn't work as expected:
```python
guidance.llm = guidance.llms.transformers.LLaMA("meta-llama/Llama-2-7b-hf", device_map="auto")
guidance("Classify sentiment. INPUT: I'm happy. OUTPUT: {{select options=['Positive', 'Negative']}}")()
```
returns the non-interpolated result:
```bash
Classify sentiment. INPUT: I'm happy. OUTPUT: {{select options=['Positive', 'Negative']}}
```
With OpenAI models it works fine:
```python
guidance.llm = guidance.llms.OpenAI("text-davinci-003")
guidance("Classify sentiment. INPUT: I'm happy. OUTPUT: {{select options=['Positive', 'Negative']}}")()
```
-->
```
Classify sentiment. INPUT: I'm happy. OUTPUT: Positive
```

**System info (please complete the following information):**
 - colab
 - Guidance Version 0.0.64:

**Comment by OscarIntellico** [comment]
The same holds for me even using the prompt in the guide.

```
prompt = guidance('''Generate a response to the following email:
{{email}}.
Response:{{gen "response"}}

Is the response above offensive in any way? Please answer with a single word, either "Yes" or "No".
Answer:{{#select "answer" logprobs='logprobs'}} Yes{{or}} No{{/select}}''')
prompt = prompt(email='I hate tacos')
prompt
```
Returns the template of the program as is

**Comment by niklub** [comment]
anything can be fixed here? @Harsha-Nori I'd appreciate it if you could indicate where to look to patch the issue. Thanks!

**Comment by jadermcs** [comment]
Having the same issue, I am using the Transformers interface and using the following prompt:
```
[...]
ANSWER: {{#select 'answer'}}identical{{or}}related{{or}}unrelated{{/select}}
```
which is decoded by guidance as:
```
[...]
ANSWER: identicalrelatedunrelatedidentical
```
It is not removing the options. Any ideas?

**Comment by marcotcr** [comment]
Hopefully this is also fixed in the [new release](https://github.com/guidance-ai/guidance/discussions/429), where we fixed a ton of select bugs. Sorry it took us so long to get to it!
