### ISSUE TITLE
Has guidance been unmaintained since Scott Lundberg moved to Google DeepMind in August 2023?

### ISSUE THREAD

**Issue by Keiku** [guidance-ai/guidance#382]
@slundberg
Looking at his Linkedin, it appears that Scott Lundberg will be moving to Google DeepMind in August 2023. The guidance seems to have stopped maintenance since then. What will the future of guidance be like?

**Comment by nmiletic** [comment]
Check pythonic branch. Very active lately

**Comment by Keiku** [comment]
Guidance has been released stably until June. It appears that the guidance release is currently inactive.

<img width="988" alt="image" src="https://github.com/guidance-ai/guidance/assets/199433/68c6e598-9afe-4127-9862-92afcf9a4121">

**Comment by dkajtoch** [comment]
@Keiku Asked the same question and no response yet

**Comment by marcotcr** [comment]
Please check [this](https://github.com/guidance-ai/guidance/discussions/429) out :)
We were inactive (both of us moved to Google), but we are back :)
