### ISSUE TITLE
Is there any documentation explaining all the syntax from the basics and what we can do with guidance?

### ISSUE THREAD

**Issue by mandar-01** [guidance-ai/guidance#383]
I couldn't understand much from the examples and want to know if there is any resource where I can learn guidance from the basics.

**Comment by gitTreeYoung** [comment]
+1, the example given is very difficult to understand

**Comment by mandar-01** [comment]
@jadermcs thanks for your explanation. This is exactly what I need, a tutorial/documentation which explains what guidance is, meaning of its syntax and keywords, and what it does, from the basics. Do you have any recommended resources/articles/topics to go through?

**Comment by jadermcs** [comment]
@mandar-01 The examples in the notebooks are straightforward after you understand what sampling is. For example, you are sampling an autoregressive language model for sentiment analysis, the traditional way would be:
```
Is this sentence positive or negative?
"I love cats."
A:
```
Without guidance is possible that the language model could return something like:
>Is this sentence positive or negative?
"I love cats."
A: **I think this sentence is positive.**

Which would be a problem if you want to parse the answers automatically. With guidance, you can do the following:
```
Is this sentence positive or negative?
"I love cats."
A: {{#select}}positive{{or}}negative{{/select}}
```
With this guidance will filter only for the tokens of positive or negative in a greedy manner. So at the end you probably will have the answer in the way you are expecting:
>Is this sentence positive or negative?
"I love cats."
A: **positive**

The notebooks have many more examples of the ways you can filter the sampling.

**Comment by antonmosin** [comment]
@slundberg authored two Medium articles that offer a nice overview:

https://medium.com/towards-data-science/the-art-of-prompt-design-use-clear-syntax-4fc846c1ebd5
https://medium.com/towards-data-science/the-art-of-prompt-design-prompt-boundaries-and-token-healing-3b2448b0be38

**Comment by marcotcr** [comment]
Sorry, our previous readme was a mess. Hopefully the one in the [new release](https://github.com/guidance-ai/guidance/discussions/429) is better.
