### ISSUE TITLE
GPU memory leak with local models

### ISSUE THREAD

**Issue by twharding** [guidance-ai/guidance#389]
**The bug**
When running longer notebooks with multiple programs, GPU memory rises with each program execution before eventually leading to an OOM error. This doesn't happen when calling model.generate(tokens) directly. 

**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.
```python
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
import guidance

model_name_or_path = "TheBloke/Llama-2-13B-chat-GPTQ"
model = AutoModelForCausalLM.from_pretrained(model_name_or_path,
                                             device_map="auto",
                                             trust_remote_code=False,
                                             low_cpu_mem_usage=True,
                                             revision="main")

tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, use_fast=True)

llama = guidance.llms.Transformers(model=model, tokenizer=tokenizer, device=0, cache=False)
guidance.llm = llama

for i in range(10):
    guidance.llms.Transformers.cache.clear()
    # define a guidance program that adapts a proverb
    program = guidance("""Tweak this proverb to apply to model instructions instead.

    {{proverb}}
    - {{book}} {{chapter}}:{{verse}}

    UPDATED
    Where there is no guidance{{gen 'rewrite' stop="\\n-"}}
    - GPT {{#select 'chapter'}}9{{or}}10{{or}}11{{/select}}:{{gen 'verse'}}""")

    # execute the program on a specific proverb
    executed_program = program(
        proverb="Where there is no guidance, a people falls,\nbut in an abundance of counselors there is safety.",
        book="Proverbs",
        chapter=11,
        verse=14
    )
```

**System info (please complete the following information):**
 - Guidance Version (`guidance.__version__`): 0.0.64

**Comment by OscarIntellico** [comment]
I think i have the same problem. 
I'm using the following models:

- **Llama2-13b-hf**  with bnb.nf4 and double quantization -> it didn't crash
- **Llama2-13b-chat-hf** with bnb.nf4 and double quantization -> crashed with a CUDA OOM error
- **WizardLM/WizardMath-13B-V1.0** with bnb.nf4 and double quantization -> crashes witha CUDA OOM error

Here's the error that i get:

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.00 MiB (GPU 0; 22.19 GiB total capacity; 20.50 GiB already allocated; 8.50 MiB free; 21.19 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by yangyaofei** [comment]
I think maybe this is the reason: https://github.com/TimDettmers/bitsandbytes/issues/784

And my workaround is :
```python
from guidance.llms import Transformers
import gc

Transformers.cache.clear()
gc.collect()
self.model.device.empty_cache()
gc.collect()
```

**Comment by marcotcr** [comment]
Hopefully this is fixed in the [new release](https://github.com/guidance-ai/guidance/discussions/429). Sorry it took us so long to get to it!

**Comment by noahdasanaike** [comment]
I'm still getting this out of memory crash on multiple different devices w/ version 0.1.5.
