### ISSUE TITLE
Selecting or highlighting content

### ISSUE THREAD

**Issue by AdamSobieski** [guidance-ai/guidance#393]
Hello. I would like to request a feature for selecting or highlighting content.

Let us consider the following prompt:

```
You are a helpful assistant.

Given the following text:

Lorem ipsum dolor sit amet, consectetur {{highlight}}adipiscing{{/highlight}} elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis knostrud exercitation ullamco
laboris nisi ut aliquip ex ea commodo consequat.

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Answer the following question:

Which of these words has the closest meaning to the highlighted word?

1) tempor
2) commodo
3) ullamcorper
4) lacus
```

This capability to select or highlight passages of text would be useful for scenarios including, but not limited to, asking LLMs language, reading, and story comprehension questions.

Also, brainstorming, perhaps multiple selections or highlights could be placed into content. With multiple highlights, there would then be a matter of how to canonically refer to each highlighted portion of content. The following example shows one possible approach:

```
You are a helpful assistant.

Given the following text:

Lorem ipsum dolor sit amet, consectetur {{highlight id="1"}}adipiscing{{/highlight}} elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis knostrud exercitation ullamco
laboris nisi ut aliquip ex ea commodo consequat.

Duis aute irure dolor in reprehenderit in {{highlight id="2"}}voluptate{{/highlight}} velit esse cillum dolore eu
fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit
anim id est laborum.

Answer the following question:

Which of these words has the closest meaning to the highlighted passage {{ref id="1"}}?

1) tempor
2) commodo
3) ullamcorper
4) lacus
```

Hopefully these ideas for features are of some interest to the Guidance team and developer community. Thank you.

**Comment by jadermcs** [comment]
What do you mean by highlight? What does this translate to asking a language model? If you want to query the language model for this part of the text, the approach is:
```
...
Which of these words has the closest meaning to the highlighted passage adipiscing?
```
As you showed, the highlight doesn't do anything to guide the decoding step.

**Comment by AdamSobieski** [comment]
@jadermcs, thank you. There are scenarios where a particular portion of selected or highlighted text might occur multiple times in natural-language content, e.g., pronouns and other anaphoric references.

Let us consider a story with numerous pronouns referring to story characters and a question about a specific pronoun instance, asking to whom it refers.

```
Text:

Alice asked Charles whether he knew where her keys were.
Before he could respond, Sally entered the room and asked Alice for the umbrella.
Alice quickly handed it to {{highlight id="123"}}her{{/highlight}}.
Sally left with the it, now better prepared for the forecast of rain.

Question:

Which story character is the highlighted content {{ref id="123"}} referring to?
```

So, the capability to select or highlight text content, in some manner, could be useful for reasons including to ensure that there are not ambiguous matches in referenced text contents.

P.S.: As interesting, visual pointing, selecting, highlighting, and indicating are utilized with respect to questions for large multimodal models (LMMs), e.g., GPT-4V. See also: _The Dawn of LMMs: Preliminary Explorations with GPT-4V(ision)_ [[pdf](https://[arxiv.org/pdf/2309.17421.pdf](https://arxiv.org/pdf/2309.17421.pdf))].

**Comment by AdamSobieski** [comment]
@jadermcs, I was thinking that Guidance would generate some text content, but potentially different such content per LLM.

If the forefront LLMs can do as you describe using any arbitrary markup elements, then there wouldn't be a need for Guidance templates for LLM-independent content selection and highlighting. Markup would work across LLMs and including with multiple selections, e.g., `<select1>...</select1>` and `<select2>...</select2>` or `<x>...</x>` and `<y>...</y>`.

**Comment by AdamSobieski** [comment]
A motivating use case for both this issue and #392 is generating questions, items, for purposes of evaluating AI systems. In these regards, I am thinking about uses of templates, of LLMs/LMMs, and of combinations thereof, e.g., Guidance, for producing large collections of high-quality questions... these generated items utilizing Guidance, again, to constrain the formatting of AI systems' output answers.

That is, beyond potential uses of Guidance for generating high-quality questions, Guidance would also, as considered, be useful as a means of constraining the output answers. As considered, this would enhance the evaluation of the outputs across types of questions.

Also, the processes of generating items needn't be entirely automated. The processes could be computer-aided, semi-automated, or otherwise have humans in the loop, e.g., humans answering or evaluating some items for quality assurance.

Humans could also, for instance, enhance computer-generated questions with cognitive models, item models, and design rationales [1]. Today, it is, as I understand it, a matter for continued R&D exploration whether and how AI systems might generate or help to generate these components for generated items. Perhaps provided with abundant examples of well-designed items, AI systems could soon generate items with these accompanying models and rationales?

Thank you for indicating markup elements as a means of selecting or highlighting spans of text in questions for LLMs, e.g., `<x>...</x>`, `<y>...</y>`, `<z>...</z>`, `<w>...</w>`.

#### References

[1] Gierl, Mark J., Hollis Lai, and Vasily Tanygin. Advanced methods in automatic item generation. Routledge, 2021.
