### ISSUE TITLE
What are the Maintaners' intentions with Guidance?

### ISSUE THREAD

**Issue by freckletonj** [guidance-ai/guidance#395]
This was my favorite "constrained generation" library, but I'm afraid it's dead. I would like to be wrong.

It's Oct 5, the last commit was >2mo ago, and maintainers have not been involved in replies, vetting Issues nor PRs, nor adding models, nor fixing bugs.

*Would you please give a status report of your intentions, or archive this project?*

If not, the community should direct their attention at a fork that isn't dead, although I don't know if those maintainers would be serious about carrying the torch. 2 forks have novel commits, and several github stars:

* https://github.com/Maximilian-Winter/guidance  adds llama-cpp-python support
* https://github.com/paolorechia/local-guidance incorporates a web ui

If not, some similar players in this space are actively maintained:

* https://github.com/eth-sri/lmql
* https://github.com/outlines-dev/outlines

**Comment by OscarIntellico** [comment]
Thank you for the suggestion of other alternatives, i was wondering the same thing about the repository status.

**Comment by marcotcr** [comment]
Not dead - we have been working on a release with lots of big changes (it's taking longer than expected).
Hoping to merge it into master soon

**Comment by freckletonj** [comment]
@marcotcr Thanks for the reply! I really did prefer this project over alternatives, but then bugs went uninspected, and PRs unmerged. 

Could you tell us about the `microsoft -> guidance-ai` shift? Who runs the project now, and do they see this as a project they'll want to maintain? I think just giving updates, maybe posting about your future dev plans, etc would go along way to keeping the wind in the community's sails.

**Comment by marcotcr** [comment]
Yes, sorry, a lot has happened. Me and @slundberg switched employers, and Microsoft moved the project out to `guidance-ai/guidance` so that we could continue working on it (they were **very nice**).

The switch took a while, and we let the project lapse in the meantime. Since we picked it back up, me and Scott have been working on [this branch](https://github.com/guidance-ai/guidance/tree/pythonic), and more recently on [this one](https://github.com/guidance-ai/guidance/tree/pythonic2) with what we thought would be a quick change, but proved to result in a larger refactor that obviates many of the current issues. I think we're close to being ready to release (as in... in a couple of weeks), at which point our plan is to write a blog post, revamp README, examples, etc, and go through all issues that are still relevant.

The new version should be _way better_, but we'll see how the community responds :)

**Comment by freckletonj** [comment]
:heart: Thanks for the update! :heart:

**Comment by Nick-tenBroeke** [comment]
Fantastic to hear this is still in development. There's nothing I found that quite gives me the control over the results of prompt chaining than guidance. Excited to see the update when it comes out. 

Syntax highlighting would be a gamechanger so hoping that's on the roadmap. 🙏

**Comment by ibehnam** [comment]
> Fantastic to hear this is still in development. There's nothing I found that quite gives me the control over the results of prompt chaining than guidance. Excited to see the update when it comes out.
> 
> Syntax highlighting would be a gamechanger so hoping that's on the roadmap. 🙏

How about LMQL? I've been thinking about using it instead of guidance but I don't know if anyone has tried both to give an unbiased comparison of them.

**Comment by Nick-tenBroeke** [comment]
> > Fantastic to hear this is still in development. There's nothing I found that quite gives me the control over the results of prompt chaining than guidance. Excited to see the update when it comes out.
> > Syntax highlighting would be a gamechanger so hoping that's on the roadmap. 🙏
> 
> How about LMQL? I've been thinking about using it instead of guidance but I don't know if anyone has tried both to give an unbiased comparison of them.

Wasn't aware of this package yet, thanks for pointing it out. From what I can see LMQL is limited to completion endpoints/model which would make it less versatile than guidance. There are some interesting ideas there though so I'll definitely check it out.

**Comment by freckletonj** [comment]
@Nick-tenBroeke guidance works on fill-in-the-middle models? I wasn't aware. I truly wish this project would revive. Last I tried it it was broken for all my use cases, and relevant issues from other users were ignored :(

**Comment by freckletonj** [comment]
I see @marcotcr  recently joined, so I guess this project may have new life at some point? https://github.com/guidance-ai/guidance/commit/302a240b35b51a8626bfb7f8b9beb28fc6359bf4

Welcome @marcotcr!

**Comment by Harsha-Nori** [comment]
Hey @freckletonj, thanks for all your interest and passion about Guidance! As Marco mentioned above, we've been focused on completely revamping guidance in the branch here: https://github.com/guidance-ai/guidance/tree/pythonic2, though these changes are still stabilizing (and therefore not ready to pull into main just yet). Lots of progress being made, just not on the default GH homepage view :)

**Comment by caillef** [comment]
> Hey @freckletonj, thanks for all your interest and passion about Guidance! As Marco mentioned above, we've been focused on completely revamping guidance in the branch here: https://github.com/guidance-ai/guidance/tree/pythonic2, though these changes are still stabilizing (and therefore not ready to pull into main just yet). Lots of progress being made, just not on the default GH homepage view :)

Hey, I would love to use the version on the branch. Even if it is not stabilised, can we still test it? Do you have a small example of the new default python file?

**Comment by marcotcr** [comment]
> I see @marcotcr recently joined, so I guess this project may have new life at some point? https://github.com/guidance-ai/guidance/commit/302a240b35b51a8626bfb7f8b9beb28fc6359bf4

> Welcome @marcotcr!

Thank you. I was developing guidance from the very beginning, just hadn't joined the board :)

---------
We finally have a [new release](https://github.com/guidance-ai/guidance/discussions/429), sorry it took us _so long_ :)
