### ISSUE TITLE
#select for yes or no always output three result 

### ISSUE THREAD

**Issue by echo-saurav** [guidance-ai/guidance#398]
Am i missing something, its always three result , yes no no 
and if i add "maybe" to the option it output four result like, yes no maybe maybe

```python
program = guidance('''Is the following sentence positive?
Please answer with a single word, either "Yes" or "No".

Sentence: {{example}}
Answer:{{#select "answer" logprobs='logprobs'}} Yes{{or}} No{{/select}}''')
executed_program = program(
        example='I love cats so much, they are so cute, i wanna cuddle them all day long'
)

print(executed_program)
print(executed_program['logprobs'])
```

output:
```md
Is the following sentence positive?
Please answer with a single word, either "Yes" or "No".

Sentence: I love cats so much, they are so cute, i wanna cuddle them all day long
Answer: Yes No Yes
{' Yes': -0.6159630747807324, ' No': -0.7767907114994823}
```

**Comment by RohanKPatil** [comment]
Faced a similar issue while using #select tag. The workaround is to use the other way of specifying options:

```
choices = ['Yes', 'No']

program = guidance('''Is the following sentence positive?
Please answer with a single word, either "Yes" or "No".

Sentence: {{example}}
Answer: {{select "answer" options=opt logprobs='logprobs'}}''')

executed_program = program(
        example='I love cats so much, they are so cute, i wanna cuddle them all day long'
        opt=choices
)
```

**Comment by marcotcr** [comment]
Hopefully this is fixed in the [new release](https://github.com/guidance-ai/guidance/discussions/429), where we fixed a bunch of select bugs. Sorry it took us so long to get to it!

**Comment by miku448** [comment]
I've made a dubious fix for the old version, in case someone needs to use select for OpenAI. It looks like the trie parser recursion and some issues by modifying the prefix while gathering the options
https://github.com/miku448/guidance/commit/08e930ab86bc5fea09e634b57d822328cb41e5bc

You can test it with my fork
guidance @ git+https://github.com/miku448/guidance@0.0.65-patch.1
