### ISSUE TITLE
how can i use guidance for next word predictions?

### ISSUE THREAD

**Issue by akashAD98** [guidance-ai/guidance#410]
**Is your feature request related to a problem? Please describe.**

i want to use gudance for predictiong newxt words or auto suggestions task similar to Google Gmail

i used below format & restricted to max_token= 7 ewords
but how can i assign the main promt?

like 
main prompt :"your best at auto suggestion or predict the next tow words, its e-commerce related work"
input: what is 
output: your  name

this is what I want

t

```
guidance.llm = guidance.llms.OpenAI("text-davinci-003") 

guidance.llms.Transformers("your_local_path/llama-7b", device=0)

# we can use the {{gen}} command to generate text from the language model
# note that we used a ~ at the start of the command tag to remove the whitespace before it (just like in Handlebars)
program = guidance('''what you do for {{~gen 'best' temperature=0.7 max_tokens=5}}''')
print(program())

```

**Comment by marcotcr** [comment]
Please check out [this section](https://github.com/guidance-ai/guidance#basic-generation) of our [new readme](https://github.com/guidance-ai/guidance/discussions/429)
