### ISSUE TITLE
any support for ggml ? want to use mistral lama2 models

### ISSUE THREAD

**Issue by akashAD98** [guidance-ai/guidance#411]
this is really helpful to use guidance with this quantized version of models.hope this feature you will release  soon

**Comment by fullstackwebdev** [comment]
might be able to use vLLM to load it, at least I was able to load a mistral AWQ with vLLM, but did not test it with guidance.

then follow these instructions? 
https://github.com/berkecanrizai/llm-stuff/tree/main/structured/vllm_guidance

Curious to hear if it works

**Comment by fullstackwebdev** [comment]
Here's a non-GGML working version:

```
model_name="HuggingFaceH4/zephyr-7b-alpha"  
import transformers   
tokenizer = transformers.AutoTokenizer.from_pretrained("HuggingFaceH4/zephyr-7b-alpha")

guideance.llm = guidance.llms.Transformers(model_name, tokenizer, device="gpu")

guidance('''The best thing about the beach is {{~gen 'best' temperature=0.7 max_tokens=7}}''')()
```

**Comment by iandennismiller** [comment]
Have a look at https://github.com/nicholasyager/llama-cpp-guidance

I've run into a few issues with old versions of packages but this has worked for me. I'm currently using Mistral-based models with llama.cpp,

**Comment by marcotcr** [comment]
This is supported in the [new release](https://github.com/guidance-ai/guidance/discussions/429), please check it out [here](https://github.com/guidance-ai/guidance#llamacpp). Sorry it took us so long :)
