### ISSUE TITLE
Traceback is print twice when error occur

### ISSUE THREAD

**Issue by tshu-w** [guidance-ai/guidance#412]
**The bug**
If an error occur the traceback message is print twice.

This is caused by the following print https://github.com/guidance-ai/guidance/blob/302a240b35b51a8626bfb7f8b9beb28fc6359bf4/guidance/_program_executor.py#L110-L113

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): macOS
 - Guidance Version (`guidance.__version__`): 0.0.64

**Comment by marcotcr** [comment]
Thanks, this is now fixed in the [new release](https://github.com/guidance-ai/guidance/discussions/429), where all error handling and debugging is much better
