### ISSUE TITLE
{{#unless @last}} does not work

### ISSUE THREAD

**Issue by SimJeg** [guidance-ai/guidance#415]
Hello, 

I am trying to generate a structured JSON output : a list of dictionaries.

If I do this : 
```python
program = guidance("""[{{#geneach 'characters' num_iterations=3}}
    {
        "name": "{{gen 'name'}}", 
        "age": "{{gen 'age'}}" 
    },{{/geneach}}
]""")
output = program()
```

I get that : 

```json
[
    {
        "name": "John", 
        "age": "27" 
    },
    {
        "name": "Jane", 
        "age": "25" 
    },
    {
        "name": "Bob", 
        "age": "30" 
    },
]
```

I am not happy with this output because of the last comma : json.loads(output.text) will fail because of it. The handlebars solution would be : 

```python
program = guidance("""[{{#geneach 'characters' num_iterations=3}}
    {
        "name": "{{gen 'name'}}", 
        "age": "{{gen 'age'}}" 
    }{{#unless @last}},{{/unless}}{{/geneach}}
]""")
output = program()
```

But I get the following error : 
```bash
KeyError: "Command/variable '@last' not found! Please pass it when calling the program (or set a default value for it when creating the program)."
```

Note that if I replace `@last` by `@first` it works as expected : there is a comma after each element of the list except the first one. Would it be possible to fix this ? 

Thanks,
Simon

**Comment by wiiiktor** [comment]
How are you able to run this at all?.. I read here that it stopped to work with new OPENAI versions and I also can not run.

**Comment by marcotcr** [comment]
We did away with handlebars support in the [new release](https://github.com/guidance-ai/guidance/discussions/429), hopefully pure python code is much cleaner :)
