### ISSUE TITLE
The select example on READMe no longer works.

### ISSUE THREAD

**Issue by amir-in-a-cynch** [guidance-ai/guidance#418]
**The bug**
The example on the main read me for using davinci to generate a proverb no longer respects `select` syntax in 0.0.64. (Still works if you downgrade to 0.0.60.) . Instead it concatenates all the options in final output.

**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.
```python
import guidance

# set the default language model used to execute guidance programs
guidance.llm = guidance.llms.OpenAI("text-davinci-003")

# define a guidance program that adapts a proverb
program = guidance("""Tweak this proverb to apply to model instructions instead.

{{proverb}}
- {{book}} {{chapter}}:{{verse}}

UPDATED
Where there is no guidance{{gen 'rewrite' stop="\\n-"}}
- GPT {{#select 'chapter'}}9{{or}}10{{or}}11{{/select}}:{{gen 'verse'}}""")

# execute the program on a specific proverb
executed_program = program(
    proverb="Where there is no guidance, a people falls,\nbut in an abundance of counselors there is safety.",
    book="Proverbs",
    chapter=11,
    verse=14
)
print(executed_program.text)
```

The output now simply concatenates all the options in the select clause (GPT 910119:14).

```
Tweak this proverb to apply to model instructions instead.
    
    Where there is no guidance, a people falls,
but in an abundance of counselors there is safety.
    - Proverbs 10:14
    
    UPDATED
    Where there is no guidance, a model fails,
but in an abundance of instructions there is safety.
    - GPT 910119:14
```

**System info:**
 - OS (Ubuntu.):
 - Guidance Version (0.0.64):

**Comment by marcotcr** [comment]
Hopefully this is fixed in the [new release](https://github.com/guidance-ai/guidance/discussions/429), where we fixed a bunch of select bugs (or bugs in general too :)). Sorry it took us so long to get to it!

**Comment by hackgoofer** [comment]
@marcotcr just linking to the new release is NOT helpful. Can you share working code samples?
