### ISSUE TITLE
Add possibility to disable "guidance acceleration"

### ISSUE THREAD

**Issue by Mihaiii** [guidance-ai/guidance#432]
Congrats on the massive redesign and on llama.cpp integration.

After this update, do I have the possibility to force the model generate hardcoded template text instead of making an extra call to the LLM (for each time I have "gen" keyword)?

My use case is that I have an extremly long system prompt and it actually takes a lot more time making lots of requests rather than constraining the "LLM wrapper" to chose the exact token that compose my template as next token (like llama.cpp's grammar does).

**Comment by slundberg** [comment]
Hey! Acceleration only works right now for local models like llama.cpp and transformers, and in those cases there is not an "extra" call, just a normal unrolling of the decoding loop but with extra bias/filters. For remote models like OpenAI or VertexAI we just run optimistically, meaning we don't make lots of calls...unless the model goes off course.

I am not sure if that totally answers your question. But I hope so :) ...basically for local models there is nothing worth disabling, and for remote models we already turn off the most expensive part whenever possible (though let us know if you run into any bugs there).
