### ISSUE TITLE
[BUG] Cannot run llama.cpp with more than 512 tokens

### ISSUE THREAD

**Issue by SimJeg** [guidance-ai/guidance#435]
Hello,

I am trying to use llama.cpp with more than 512 tokens. I succeeded doing it using :

```python
from llama_cpp import Llama

n_ctx = 1024
max_tokens = 10
prompt = "Repeat after me:" + "I am Scott ! " * 200 + 'What is your name ? My name is '
model_path = '.../llama-2-7b-chat.Q4_K_M.gguf'

llm = Llama(model_path, n_ctx=n_ctx)
llm(prompt, max_tokens=max_tokens, stop=['!'])
```

But failed using the following : 

```python
from guidance import gen
from guidance.models import LlamaCpp

[...]

llm = LlamaCpp(model_path, n_ctx=n_ctx)
llm + prompt + gen(max_tokens=max_tokens, stop='!')
```

I get the following error : 

```bash
GGML_ASSERT: /tmp/pip-install-545alk6o/llama-cpp-python_c520816676e04d9c86fdac163e9f599e/vendor/llama.cpp/llama.cpp:5373: n_tokens <= n_batch
```

Note that if you use a prompt shorter than 512 tokens, for instance replacing `* 200` by `* 100`, both work.

I was able to fix this issue by adding `n_batch=n_ctx` in the arguments, maybe this should be done by default in `LlamaCpp` ?

**Comment by slundberg** [comment]
Thank you for tracking this down! I am not sure why batch sizes smaller than n_ctx are causing issues, but I added a quick patch for now that updates n_batch whenever n_ctx is set. (in the future we are going to use a new part the llama.cpp API and that might help address this so we can have variable batch sizes.

**Comment by paulbkoch** [comment]
The new Llama.cpp API does indeed address this.  PR #455 transitions to the new API.
