### ISSUE TITLE
Add gen-like arguments to substring 

### ISSUE THREAD

**Issue by SimJeg** [guidance-ai/guidance#439]
Hello,

Following [this issue](https://github.com/guidance-ai/guidance/issues/433) (thanks @marcotcr for the quick reply !), would it be possible to add more `gen` arguments in the `substring` component ?

For instance `name` to save the result of the generation, `regex` to allow only substrings that respect a given pattern,`max_tokens` to limit the generation, `stop` to stop it etc.

This `substring` is really great because it limits hallucinations, thanks for it :) 

Thanks,
Simon

**Comment by marcotcr** [comment]
Hi there. We really need to document the features in the grammar library, but in the meantime he is an example where we:
1. Save the result of a generation in a variable, using `capture`, even when something is optional
2. Set `max_tokens` only on part of the grammar, using `token_limit`

```python
from guidance import capture, substring, select, regex, token_limit
# Either substring or a number with at most one token
grammar = select(
        [capture(substring('This is very cool.'), name='substring'),
         token_limit(capture(regex('\d+'), name='number'), 1)])
lm = llama2 + 'Hi there, here is a sentence "' + (grammar + '"')
```

```python
lm = llama2 + 'Hi there, here is a sentence "' + (grammar + '"')
lm['substring']
```
> Hi there, here is a sentence "This is very cool."

```python
lm = llama2 + 'Hi there, here is a number: ' + grammar
lm['number']
```
> Hi there, here is a number: 123
