### ISSUE TITLE
Support for DSL grammars

### ISSUE THREAD

**Issue by rkrishnasanka** [guidance-ai/guidance#44]
**Is your feature request related to a problem? Please describe.**
Seeing that guidance has some ability to generate syntax specific outputs, I'm curious to know if the team has thoughts on generating more complex programming language grammars. 

**Describe the solution you'd like**

When the points to a reference syntax, the llm output would be syntactically correct specific to the given language grammar.

**Describe alternatives you've considered**
None

**Additional context**
I have a bunch of domain specific languages I've built and I've been thinking that if I can basically validate each token that comes out of the stream against a language grammar, it should basically ensure that it works correctly all the time. It's kind of an extension of the valid options you have in the examples.

I'm happy to help build this but I'd need some help is outlining this.

**Comment by marcotcr** [comment]
We [now](https://github.com/guidance-ai/guidance/discussions/429) support any [Context-Free grammars](https://github.com/guidance-ai/guidance#context-free-grammars) :)
Sorry it took us so long to get to this
