### ISSUE TITLE
Answer doesn't go beyond 100 tokens

### ISSUE THREAD

**Issue by zakariaboualaid** [guidance-ai/guidance#451]
**The bug**
I am a bit unsure if this is a bug or not, forgive me if it's not. I am using the latest version `0.1.1`. I am using OpenAI and trying a simple example :

```
    gpt = guidance.models.OpenAI("gpt-3.5-turbo", temperature=0.2)
    
    with system():
        lm = gpt + "You are an expert at something:\n"
        lm += some_text
        
    with user():
        lm += "What's your feedback on the following:\n"
        lm += some_text

    with assistant():
        lm += gen("answer")
  ```

The answer is always 100 tokens and doesn't go beyond that, I tried using `max_tokens` in the `gen` function like :
`gen("answer", max_tokens=500)`, but that also did not work.

I also tried to increase max_tokens in the first line when I am calling the model, that also did not work.

Am I doing something wrong?

**Comment by slundberg** [comment]
Thanks for bringing this up! That was unfortunately driven by a simple naming bug where the max_streaming_tokens param was being ignored. Sorry about that, it is now fixed on main :)
