### ISSUE TITLE
AssertionError when using `<|im_start|>` and `<|im_end|>` tags in prompt

### ISSUE THREAD

**Issue by cschneid** [guidance-ai/guidance#479]
**The bug**
AssertionError when using `<|im_start|>` and `<|im_end|>` tags.

**To Reproduce**

### Script
```python
from guidance import models, gen

model_path = '/Users/cschneid/.cache/lm-studio/models/TheBloke/OpenHermes-2.5-Mistral-7B-16k-GGUF/openhermes-2.5-mistral-7b-16k.Q5_K_M.gguf'
llama2 = models.LlamaCpp(
  model=model_path,
  n_gpu_layers=1,
)

system_message = 'You are a professional editor. List every grammar error'
user_prompt = '.... whatever ...'

prompt = f'''
<|im_start|>system
{system_message}
<|im_end|>
<|im_start|>user
{user_prompt}
<|im_end|>
<|im_start|>assistant
'''

print(prompt)
print(llama2 + prompt + gen(stop='.'))
```

### Output:
```
<|im_start|>system
You are a professional editor. List every grammar error
<|im_end|>
<|im_start|>user
.... whatever ...
<|im_end|>
<|im_start|>assistant

Traceback (most recent call last):
  File "/Users/cschneid/Code/llm/first_guidance.py", line 23, in <module>
    print(llama2 + prompt + gen(stop='.'))
          ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
  File "/Users/cschneid/miniconda3/envs/ai/lib/python3.11/site-packages/guidance/models/_model.py", line 242, in __add__
    out = lm._run_stateless(value)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cschneid/miniconda3/envs/ai/lib/python3.11/site-packages/guidance/models/_model.py", line 382, in _run_stateless
    for new_bytes, is_generated, new_bytes_log_prob, capture_groups, capture_group_log_probs, new_token_count in gen_obj:
  File "/Users/cschneid/miniconda3/envs/ai/lib/python3.11/site-packages/guidance/models/_local.py", line 119, in __call__
    token_ids,token_byte_positions = self._cleanup_tokens(token_ids,token_byte_positions)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cschneid/miniconda3/envs/ai/lib/python3.11/site-packages/guidance/models/_local.py", line 101, in _cleanup_tokens
    assert token_byte_positions[-1] == last_pos
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

#### Similar error:
If I remove the start & end tags from the prompt, I get a different error, which may be related to #475 

```
UnboundLocalError: cannot access local variable 'sampled_token' where it is not associated with a value
```

#### Other Models?
Maybe this is related to Mistral vs. Llama derived models? I grabbed llama-2-7b-32k-instruct.Q5_K_M.gguf and couldn't reproduce this with its prompt template.

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): Mac OS
 - Guidance Version (`guidance.__version__`): 0.1.4

**Comment by slundberg** [comment]
You probably want to use the role tags:
<img width="774" alt="image" src="https://github.com/guidance-ai/guidance/assets/3740613/f5525269-c63c-4473-b8b2-53d85474388a">

The put the special tokens that are correct for the model in there. And if there is a not a model class that knows the right tokens to put in, you can make your own subclass and just override the `get_role_start` and `get_role_end` methods.

**Comment by slundberg** [comment]
...so I managed to reproduce the error. Will share if/when I find a fix.

**Comment by slundberg** [comment]
<img width="794" alt="image" src="https://github.com/guidance-ai/guidance/assets/3740613/547f32d9-3bc4-4adc-b5c5-4fc372766b13">


fixed now :)

**Comment by BardiaKh** [comment]
Hi @slundberg,

I am trying to have custom class for a chat model subclassed from `TransformersChat` (not `LlamaCppChat`):

```python
from guidance.models import TransformersChat

class ZephyrChat(TransformersChat):    
    def get_role_start(self, role_name, **kwargs):
        role_dict = {
            'user': "<|user|>\n",
            'assistant': "<|assistant|>\n",
            'system': "<|system|>\n"
        }
        return role_dict.get(role_name, '')
    
    def get_role_end(self, role_name=None):
        return "</s>\n"
```
Then:
```python
chat_lm = ZephyrChat(model, tokenizer, echo=False)

with user():
    lm = chat_lm + 'Do you want a joke or a poem?'

with assistant():
    lm += f"A {select(['joke', 'poem'])}."
```

But I get a similar error:
![image](https://github.com/guidance-ai/guidance/assets/13269112/5b5c1d2f-4cfb-413c-8117-a4090613eabe)
When I use the model in a non-chat format it works fine. Any chance you can look into it?
