### ISSUE TITLE
Why the parameters of openai api like top_p and temperature is fixed?

### ISSUE THREAD

**Issue by POFK** [guidance-ai/guidance#480]
**The bug**

When I use my self-hosted llm model with OpenAI like api, I found guidance always set the temperature as 0. However, because some reasons, my llm model will always return nothing when the temperature is 0.

After checking the source code corresponding to the OpenAI, I found the parameters like top_p and temperature are fixed and can't be passed through argument.

Is there any reason for this design?

The source code about this problem please see https://github.com/guidance-ai/guidance/blob/510200bf9c3756bcc5a49f67bfdbde2b10139ab2/guidance/models/_openai.py#L87-L95

**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.

**Comment by slundberg** [comment]
Thanks! No reason, other than we forgot to patch that through. (for local models temperature is controlled in the grammar, for remote endpoints we can't change the temp so easily so we actually care about the default temp set in the constructor)

**Comment by POFK** [comment]
> Thanks! No reason, other than we forgot to patch that through. (for local models temperature is controlled in the grammar, for remote endpoints we can't change the temp so easily so we actually care about the default temp set in the constructor)

Thanks for your reply! 
An option to control the temperature parameter is very useful for me, should I pull a request to fix it?

**Comment by cnlnpjhsy** [comment]
Also need to modify OpenAI generation parameters. I use `response_format={"type": "json_object"}` in the prompt when calling newer gpt-3.5 models, but guidance does not allow me to add this parameter. It dissuades me from using guidance 0.1 (0.0.65 could do that)😣
