### ISSUE TITLE
KeyError on result variable using gen(max_tokens >=1000) on local models

### ISSUE THREAD

**Issue by giorgiopiatti** [guidance-ai/guidance#481]
**The bug**
Setting the argument of the function generation: max_tokens to a value above 1000 on local model, doesn't allow to capture the result of the variable.

I assume this is the case, because the default value of the function `_run_stateless` is 1000, see [guidance/models/_model.py#L358](https://github.com/guidance-ai/guidance/blob/5aa48c6f6668152e338f2b96566e27c638ae871b/guidance/models/_model.py#L358),  and when called the max_tokens set by `gen` is not passed.

**To Reproduce**

```python
    with user():
        model += "Count until 1000: 1. 2. 3."

    with assistant():
        model += gen(name="test_1", max_tokens=999)
        print(model["test_1"]) # OK
        model += gen(name="test_2", max_tokens=1001)
        print(model["test_2"]) # KeyError: 'test_2'
```

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): Ubuntu 22.04.03
 - Guidance Version (`guidance.__version__`): 0.1.4

**Comment by slundberg** [comment]
Thanks @giorgiopiatti ! I bumped that to 2k for the moment, and will more deeply into it to see if we can fully remove that. The limit is a backstop to make sure remote streaming endpoints don't run forever in case something goes wrong, but there might be better ways to deal with that.

**Comment by giorgiopiatti** [comment]
Thanks! Is there a reason why the `max_tokens` args is not passed to `_run_stateless` ? I think somewhere you can keep the limit, but we should be able to choose any maximum tokens which fits into the LLM context length. 

The first uses case that I'm thinking that can be impacted by a limit would be: chain of thought prompting.
