### ISSUE TITLE
Can't seem to make any examples work with vertexAI

### ISSUE THREAD

**Issue by Ben-Epstein** [guidance-ai/guidance#505]
**The bug**
None of the provided jupyter notebook examples work for text bison. Many examples also seem to fail for the suggested models.

Bison example that doesn't work
```
from guidance import models, gen, instruction

model + "What is the capital of italy?" + gen()
```

The exception is just `Exception: This model cannot handle prompts that don't match the instruct format!`

Reading through the code, I see a suggestion such as 
```
prompt = "what is the capital of italy?"
with instruction():
    model += prompt
    model += gen(max_tokens=10)
```

But this fails as well with the same error. 

OpenAI also fails with the example [here](https://github.com/guidance-ai/guidance/blob/main/notebooks/pythonic.ipynb)
```
import guidance

# define a guidance program that adapts a proverb
@guidance
def program(lm, proverb, book, chapter, verse):
    return lm(f"""Tweak this proverb to apply to model instructions instead.

{proverb}
- {book} {chapter}:{verse}

UPDATED
Where there is no guidance""").gen("rewrite", stop="\n-")("""
- GPT """).select("chapter", options=[9, 9, 11], suffix=":").gen("verse")

lm = guidance.models.OpenAI("text-davinci-003", caching=False)

# execute the program on a specific proverb
out = program(lm,
    proverb="Where there is no guidance, a people falls,\nbut in an abundance of counselors there is safety.",
    book="Proverbs",
    chapter=11,
    verse=14
)
out["verse"]
```
error: `TypeError: 'StatefulFunction' object is not subscriptable` -- I can't seem to figure out what to do with the `out` object. 

**To Reproduce**
Any of the examples above should be runnable

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): Ubuntu
 - Guidance Version (`guidance.__version__`):`'0.1.5'`

**Comment by marcotcr** [comment]
Just as in [the readme example](https://github.com/guidance-ai/guidance#vertex-ai), the VertexAI models expect the prompt in the `instruction()` block, and the `gen` to occur outside of it. Try this:
```python
prompt = "what is the capital of italy?"
with instruction():
    model += prompt
model += gen(max_tokens=10)
```

**Comment by marcotcr** [comment]
The OpenAI example you pasted here is outdated, please try the examples in the readme

**Comment by slundberg** [comment]
@Ben-Epstein I am sorry for the trouble that outdated notebook gave you. We are working through them, but that was a particularly bad one because it had an early (now incorrect) version of the pythonic interface. I have dropped that so that hopefully others won't have the same experience :)
