### ISSUE TITLE
Python scripts return IPython HTML: <IPython.core.display.HTML object>

### ISSUE THREAD

**Issue by dnhkng** [guidance-ai/guidance#506]
With the following code:
```
import guidance
from guidance import gen, models

print(f"{guidance.__version__=}")
llama2 = models.LlamaCpp("./models/mistral-7b-instruct-v0.1.Q8_0.gguf")
llama2 + f"Do you want a joke or a poem? " + gen(stop=".")
print("done")
```
In a Jupyter Notebook, I get:
```
Do you want a joke or a poem? I can do both
done
```
In this example, the text  `guidance.__version__='0.1.5'` is briefly shown before being overwritten by `Do you want a joke or a poem? I can do both`.

As a script, I get the output:
```
$ python test_lmql.py
guidance.__version__='0.1.5'
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
done
Exception ignored in: <function _LlamaContext.__del__ at 0x7f8d152b2710>
Traceback (most recent call last):
  File "/home/dnhkng/miniforge3/envs/piper2/lib/python3.10/site-packages/llama_cpp/llama.py", line 422, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _LlamaModel.__del__ at 0x7f8d152b17e0>
Traceback (most recent call last):
  File "/home/dnhkng/miniforge3/envs/piper2/lib/python3.10/site-packages/llama_cpp/llama.py", line 240, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _LlamaBatch.__del__ at 0x7f8d152b3b50>
Traceback (most recent call last):
  File "/home/dnhkng/miniforge3/envs/piper2/lib/python3.10/site-packages/llama_cpp/llama.py", line 670, in __del__
TypeError: 'NoneType' object is not callable
```

I would really like to use this package, but outside of Juptyer, I am having trouble understanding how it should be used correctly.

**Comment by gaimstud-io** [comment]
I'm not sure about the TypeErrors, but the <IPython.core.display.HTML object> in the terminal window are the same tokens that are being rendered in your notebook. The Jupyter notebook is able to render them, the terminal is not. There is probably a way to suppress the token stream, but I haven't bothered to find it yet.

To access the generated text, give your gen call a name:

`gen(name='joke_or_poem', stop='.')`

And then access it using the model object:

`print(llm['joke_or_poem'])`

**Comment by dnhkng** [comment]
> To access the generated text, give your gen call a name:
> 
> `gen(name='joke_or_poem', stop='.')`
> 
> And then access it using the LM object:
> 
> `print(llama2['joke_or_poem'])`

Are there other ways to access the previous responses? I can imagine having a function that prompts the LLM that's called repeatedly and then labeling the correct responses might be tricky. Can we access this via a state dict or list?

**Comment by slundberg** [comment]
@dnhkng you can get the full lm state using `str(lm)` (which is the same as what would show up in the notebook without the formatting). 

I also just pushed support for named blocks:
```python
with block("my_text"):
    lm += "This is"
    lm += gen("text", max_tokens=10)
print(lm["my_text"])
```

**Comment by mcchung52g** [comment]
> @gaimstud-io is right :). You can suppress the token stream by setting `echo=False` in the init of the `guidance.models` object, eg:
> 
> ```python
> llama2 = models.LlamaCpp("./models/mistral-7b-instruct-v0.1.Q8_0.gguf", echo=False)
> ```
> 
> which will prevent non-Jupyter/ipython displays from displaying this:
> 
> ```
> <IPython.core.display.HTML object>
> <IPython.core.display.HTML object>
> <IPython.core.display.HTML object>
> <IPython.core.display.HTML object>
> <IPython.core.display.HTML object>
> <IPython.core.display.HTML object>
> <IPython.core.display.HTML object>
> ```

echo=False turns off all outputs :(
