### ISSUE TITLE
Simple tool not working as exptected

### ISSUE THREAD

**Issue by wmiller** [guidance-ai/guidance#507]
**The bug**
I've written a simple tool to constrain emote tags in dialogue. The tool's "call" function watches for `*`, then picks from a list of valid emotes. The setup is very similar to the calculator example in the documentation, but produces no output. I'm not sure if this is a bug or a misunderstanding of how tools work in Guidance.

**To Reproduce**
Here is a simple program demonstrating the issue. `get_lm()` should load a local model.
```python
import guidance
from guidance import select, gen, system, user, assistant, Tool

@guidance(stateless=True)
def emote_call(lm):
    '''The tool should be invoked when * is encountered.'''
    return lm + '*'

@guidance()
def emote(lm):
    return lm + select(['smiles', 'frowns']) + '*'

emote_tool = Tool(emote_call(), emote)

def speak():
    lm = get_lm()

    with system():
        lm += '''You are a helpful, emotive assistant. Here is an example of how to emote:\n*smiles* Hello!'''
    with user():
        lm += "*smiles* Hello. How are you today?"
    with assistant():
        lm += gen('response', tools=[emote_tool])
    
    print(lm['response'])

if __name__ == "__main__":
    speak()
```

I've verified that the tool is being invoked with an extra print statement in emote(), but the output never has the emote tag as expected. Interestingly, there is a single space at the beginning of the output where the emote should be when running with tools. Without tools, there is no space at the beginning of the output.

**System info (please complete the following information):**
 - Windows 11
 - Guidance Version 0.1.6

**Comment by slundberg** [comment]
Thanks @wmiller  for reporting this! It looks like the tool output is not getting recorded correctly in the capture group. So if you call `str(lm)` it will show up, but it is not captured in the `response` variable.

Will leave this open until we fix it.

See example below:
<img width="1011" alt="image" src="https://github.com/guidance-ai/guidance/assets/3740613/8a4623d0-6c90-42e1-bf39-1eab11b7ea01">
