### ISSUE TITLE
AzureOpenAIChat: TypeError: expected string or bytes-like object, got 'tuple' when in a loop

### ISSUE THREAD

**Issue by thisisran** [guidance-ai/guidance#509]
**The bug**
When I have a 'regular' chat structure in a loop (with system, with user, with assistant), I get the following error (on the second iteration of the loop): 

(originating from: /guidance/models/_remote.py", line 190, in _get_logits)

role_end_str = format_pattern.sub("", role_end_str)
TypeError: expected string or bytes-like object, got 'tuple' 

Unless I add the creation of the initial llm object in the loop, **then it works**

**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.
```python
import os
from guidance import models, gen, system, user, assistant
import guidance

os.environ["AZURE_OPENAI_KEY"] = "my azure api key"
os.environ["AZURE_OPENAI_ENDPOINT"] = "my azure endpoint"
os.environ["OPENAI_API_VERSION"] = 'my_api_version'

llm = models.AzureOpenAIChat(model='gpt-4',
                                 api_key=os.environ["AZURE_OPENAI_KEY"],
                                 azure_endpoint=os.environ["AZURE_OPENAI_ENDPOINT"],
                                 api_version=os.environ["OPENAI_API_VERSION"], echo=False)

for i in range(5):

    with system():
       lm = llm + "You will just return whatever number I give you"
       
    with user():
       lm += f'The number is: {i}'
       
    with assistant():
       lm += gen(name='answer')
       
```

But with the llm = models..... line included in the for loop above the "with system()" line, it works.

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): Mac OS
 - Guidance Version (`guidance.__version__`): 0.1.7

**Comment by riedgar-ms** [comment]
I can reproduce in the AzureAI side of things; no idea if the OpenAI classes have the same bug.

Adjusting the look a little to be:
```python
for i in range(5):
    print(f"Iteration: {i}")
    with system():
       lm = llm + "You will just return whatever number I give you"
       
    with user():
       lm += f'The number is: {i}'
       
    with assistant():
       lm += gen(name='answer')

    print(str(lm))
    print("\n\n")
```
I can see that the first iteration does work.

**Comment by riedgar-ms** [comment]
In the meantime, I can confirm that moving the creation of the original model inside the loop works, namely:
```python
def test_azureai_openai_chat_loop():
    azureai_endpoint = _env_or_skip("AZUREAI_CHAT_ENDPOINT")
    azureai_key = _env_or_skip("AZUREAI_CHAT_KEY")
    model = _env_or_skip("AZUREAI_CHAT_MODEL")

    for i in range(5):
        print(f"Iteration: {i}")
        lm = models.AzureOpenAI(
            model=model, azure_endpoint=azureai_endpoint, api_key=azureai_key
        )
        assert isinstance(lm, models.AzureOpenAIChat)
        with system():
            generation = lm + "You will just return whatever number I give you"

        with user():
            generation += f"The number is: {i}"

        with assistant():
            generation += gen(name="answer")

        print(str(lm))
        print("\n\n")
```

I do see a lot of calls to `Model.copy()` going on for each of the operators in the loop, and that method's comments specifically note that a shallow copy is done, and then deepened for a few particular variables.

Also, stepping with the debugger, the offending line is only hit on the second time through the loop. This is making me suspect that the problem is with some lingering state.

**Comment by riedgar-ms** [comment]
For example, later in `_model.py` I see:
```python
        lm = self.copy()

        # inside this context we are free to drop display calls that come too close together
        with throttle_refresh():

            # close any newly closed contexts
            for context in list(reversed(lm.opened_blocks)):
                if context not in Model.open_blocks and context in lm.opened_blocks:
```
So the reference to `Model.open_blocks` .... well, I've not dug into that bit of Python before, but presumably, it's trying to refer to some state shared across all instances of `Model` rather than the current model held by `self` (or `lm` at this point in the method).

**Comment by slundberg** [comment]
Okay, I dug into this and it looks like it was a bug that got introduced after the recent addition of named blocks. I just pushed a fix. Thanks for reporting this @thisisran and for tracking it down @riedgar-ms !

**Comment by thisisran** [comment]
Thank you for the quick response guys and addressing it this quickly!
