### ISSUE TITLE
AzureOpenAI + @guidance decorator + Chat model: AttributeError

### ISSUE THREAD

**Issue by thisisran** [guidance-ai/guidance#516]
**The bug**
When using the AzureOpenAI Chat class with a method defined with the @guidance decorator, I get the following error:

guidance/models/_model.py", line 299, in __add__
out._inplace_append("")

AttributeError: 'NoneType' object has no attribute '_inplace_append'

**To Reproduce**
```python
import os
from guidance import models, gen, system, user, assistant
import guidance

@guidance
def fastest_horse(lm):

    with system():
        lm += "You are an expert horse breeder"

    with user():
        lm += 'What is the fastest horse?'

    with assistant():
        lm += gen(name='answer')

llm = models.AzureOpenAI(model='gpt-4',
                         api_key=os.environ["AZURE_OPENAI_KEY"],
                         azure_endpoint=os.environ["AZURE_OPENAI_ENDPOINT"],
                         api_version=os.environ["OPENAI_API_VERSION"], echo=False)

result = llm + fastest_horse()

print(result['answer'])

```

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): Mac OS
 - Guidance Version (`guidance.__version__`): 0.1.7 (After the 26554b05619347be666647a2ac97a6a51f467bfd commit)

**Comment by slundberg** [comment]
This is because all guidance functions need to return the modified model (so `return lm` at the end of the function). I'll leave this issue open though because we need a much better error message for this :)

**Comment by thisisran** [comment]
Got it, thank you! so then the Azure tutorial/example needs to be updated in the @guidance example :)

**Comment by slundberg** [comment]
Ah! Sorry about that being off in the tutorial. Done :)
