### ISSUE TITLE
generated test: a<|im_end|>

### ISSUE THREAD

**Issue by wiiiktor** [guidance-ai/guidance#521]
I have this a<|im_end|> popping out in Guidance generations from time to time (example below). I see that this is used in guidance code, so seems to be a bug. How can I stop |im_end| from appearing? 

<img width="815" alt="image" src="https://github.com/guidance-ai/guidance/assets/41764319/1b9b3f97-c5ad-4dbb-a812-366486228d16">

**Comment by slundberg** [comment]
thanks for reporting this! Can you give an example we can use to reproduce it? It might be because you are using a chat model without using the chat role tag markers for example, or it could be a bug...

**Comment by wiiiktor** [comment]
I added the system/user/assistance structure and indeed, I do not see a<|im_end|> anymore, but the letter "a" stayed :) It even appears twice in a row from time to time. 

<img width="819" alt="image" src="https://github.com/guidance-ai/guidance/assets/41764319/390a34ea-a9bd-4e05-9db6-813955009e93">

**Comment by slundberg** [comment]
which model/tokenizer are you using? Those 'a's look like a tokenization issue

**Comment by wiiiktor** [comment]
I am not 100% sure now, sorry, but I think it was this one: 01-ai/Yi-34B-Chat
I do not have this error, after I switched to Weyaxi/OpenOrca-Zephyr-7B
(I am testing different models today...)

**Comment by slundberg** [comment]
I found the issue and a fix is now in 7bfd7609b3b42825c20e0c658368fd96c549f8e2. So once that merges the "a"'s should  be gone :)
