### ISSUE TITLE
is there any notebook example that works ? (all those I tried are obsolete)

### ISSUE THREAD

**Issue by younes-io** [guidance-ai/guidance#526]
**The bug**
I spent hours for days trying to make one single example on guidance work... (Im using Azure OpenAI API), and I can't manage to do that.. I got a few errors, but the main reason it's failing is because most of these notebooks are **obsolete** unfortunately.. 

If `guidance` re-invents its API & its modules every release, then maybe its better to have those notebooks / examples associated with the `guidance` version that was used to test them.. I have taken at least 5 examples, and none of them works.. it's really unproductive :/

**Comment by wiiiktor** [comment]
I made some kaggle / colab notebooks: 
https://github.com/guidance-ai/guidance/discussions/527 
https://github.com/guidance-ai/guidance/discussions/520

**Comment by younes-io** [comment]
@wiiiktor : are you aware of any other alternatives ?

**Comment by younes-io** [comment]
![image](https://github.com/guidance-ai/guidance/assets/3153107/f75c8262-f61c-4d98-be7e-f22c814364bc)

For instance, I downloaded this notebook from the repo examples and I'm using guidance `0.1.5` and you can see the `AzureOpenAIChat` class doesn't even exist.. am I supposed to keep decrementing the `guidance` version and install until it works ???

This isn't the only _broken_ example I came across..

**Comment by wiiiktor** [comment]
I started using guidance after 1.0 release :) and have no clue about anything that worked earlier, sorry...

**Comment by younes-io** [comment]
@slundberg : Do you have an idea of when will this be released ?
https://github.com/guidance-ai/guidance/commits/ed07f12a5c3ee41d6aeac71755caf1c9d9d30c7b/guidance/models/_azure_openai.py

I can't install the 0.1.6 even though it's in the releases in GH.. When will access to Azure Open AI classes be possible ??

**Comment by wiiiktor** [comment]
no idea, srry...

**Comment by Harsha-Nori** [comment]
Hey @younes-io, we're working through the notebooks and updating them slowly, but apologies for many of them still being out of date. The best source of documentation at the moment is our README as we get through this (and we could also use help updating the notebooks if anyone is looking to make PRs!). 

Perhaps we could shift all the old notebooks into a clearly marked folder to prevent this confusion while we transition the notebooks over? What do you think?

For getting pre-release code, you can install from source on main by cloning the repo and running:
`pip install pybind11`
`pip install -e .` 

from the repo root. We'll push out a proper PyPI update in the near future but hope this helps in the short term

**Comment by younes-io** [comment]
Hi @Harsha-Nori ,
I'm okay with anything that would help prevent this confusion.. whatever you see fit :) 
I'll try the workaround in the meantime and will try to stick to the README example until I get sth working.. For the PRs, I'd be glad to do that but I can't afford to now since I've never been able to run guidance code using Azure OpenAI API and Active Directory (which are the only two options I have to call LLMs). Until then, I'll keep an eye on the repo :)
Thank you for your feedback and for your great work! This library is really awesome and I really am looking forward to integrating it to my code!

**Comment by marcotcr** [comment]
These ones use the new version, but none use Azure: [tutorial.ipynb](https://github.com/guidance-ai/guidance/blob/main/notebooks/tutorial.ipynb), [chat_with_search.ipynb](https://github.com/guidance-ai/guidance/blob/main/notebooks/chat_with_search.ipynb), [code generation](https://github.com/guidance-ai/guidance/blob/main/notebooks/code_generation.ipynb).

**Comment by slundberg** [comment]
Courtesy of @riedgar-ms we do have one Azure one: https://github.com/guidance-ai/guidance/blob/main/notebooks/tutorial_azureai_openai.ipynb

And I second the apologies about out of date notebooks. We planned to update them faster, and hesitated to rename ones that would break external links.

**Comment by younes-io** [comment]
@slundberg : seems like the link you shared is broken and I don't find anything in the notebooks related to Azure OpenAI.

![image](https://github.com/guidance-ai/guidance/assets/3153107/da0defb8-c1c4-49bd-852c-f09118f23d56)

**Comment by younes-io** [comment]
@slundberg : I think this is the new link : https://github.com/guidance-ai/guidance/blob/main/notebooks/api_examples/models/AzureOpenAI.ipynb

I'll test it and let you know :) Thank you

**Comment by younes-io** [comment]
I added this PR https://github.com/guidance-ai/guidance/pull/583 to expose the `azure_deployment` argument which is necessary for API Key Auth on Azure (since there are two ways to connect on Azure OpenAI API);


```python
from guidance import models, gen
import tiktoken

azureai_model = models.AzureOpenAI(
    model='gpt-3.5-turbo',
    azure_endpoint=azure_endpoint,
    azure_deployment='my_crazy_deployment_name',
    api_key=api_key,
)
```

**Comment by slundberg** [comment]
We have updated lots of notebooks so hopefully this is not a big issue anymore. Closing for now, feel free to flag more.
