### ISSUE TITLE
`UnsupportedOperation: fileno` on Google Colab

### ISSUE THREAD

**Issue by cpcdoy** [guidance-ai/guidance#545]
**The bug**

Using Guidance with a `LlamaCpp` backend (the only backend I tried, so it might happen with others too) leads to an `UnsupportedOperation: fileno` on Google Colab.

**The cause**

I think this might be happening because of the way Google Colab handles the `sys.stdout` and `sys.stderr` objects:
- On Google Colab the `sys.std*` objects use `ipykernel`'s implentation `ipykernel.iostream.OutStream` which raises an `io.UnsupportedOperation` exception as can be seen in their implementation [(see Github link)](https://github.com/ipython/ipykernel/blob/4001f8af9dc46e97735a46f20ca247075fb35dcb/ipykernel/iostream.py#L363C22-L363C22)
- In a local Python 3.11 interpreter, the objects are of type `_io.TextIOWrapper`. They do contain a `fileno` method that returns the correct file descriptor [(see Python doc)](https://docs.python.org/3/library/io.html#io.IOBase.fileno)

**To Reproduce**

Open a Colab Notebook and paste in the following code with current latest `guidance` version (`0.1.8`):

```python
from guidance import user, assistant

# load a chat model
chat_lm = models.LlamaCppChat(path) # A GGUF model

# wrap with chat block contexts
with user():
    lm = chat_lm + 'Do you want a joke or a poem?'

with assistant():
    lm += f"A {select(['joke', 'poem'])}."
```

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): `Google Colab`
 - Guidance Version (`guidance.__version__`): `0.1.8`

**Comment by fabianwinter93** [comment]
I had this error before. What worked for me was when I set verbose=True.

**Comment by slundberg** [comment]
Hopefully this will be solved on the llama-cpp-python side at some point, but for now I added a patch on our side.
