### ISSUE TITLE
TypeError: Model._report_failed_match() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by CorentinvdBdO** [guidance-ai/guidance#552]
**The bug**
Return the error "TypeError: Model._report_failed_match() takes 1 positional argument but 2 were given"

**Source of the issue**
https://github.com/guidance-ai/guidance/blob/8418ea6645568cdfb639f00ce4b7ad39d81a1c2d/guidance/models/_model.py#L936
```raise self._report_failed_match(trimmed_prompt_prefix + parser.bytes)```

while the method only has self as an argument:
https://github.com/guidance-ai/guidance/blob/8418ea6645568cdfb639f00ce4b7ad39d81a1c2d/guidance/models/_model.py#L621C5-L624C1
```
def _report_failed_match(self):
        """Note that this can be overridden by subclasses that have more likely reasons than a bug in the token set (like remote models)."""
        return Exception("We can't consume any more tokens, but we are not yet done! Perhaps your model's token set is incomplete?")
```

**Comment by slundberg** [comment]
Thanks @CorentinvdBdO ! I pushed a fix for this, but it looks like this is happening for a local model, so as the exception message will now say, there might be token set issue.
