### ISSUE TITLE
Hiding the content of prompt with guidance!

### ISSUE THREAD

**Issue by akkasi** [guidance-ai/guidance#563]
**The bug**
When I run my code to generate something, all contents of the prompt appears in the output. In the previous version of guidance it was possible to hide the prompt content using {#block hidden=True}  option.  is there any solution for this problem?

**Comment by marcotcr** [comment]
If you just want to hide the prompt in the jupyter notebook output, use the following:

```python
from guidance import silent
# Anything in this block will be visible to the LM, but won't show up in the notebook visualization
with silent():
    lm += 'Content here...'
```

If you want to hide part of the prompt or generation from future generations (which is what `block hidden=True` used to do), you can just instantiate a new LM, e.g.
```python
lm = 'Here is a prompt ' + gen(max_tokens=10)
lm2 = lm
lm2 += 'I\'m adding more content / generation here, and the original lm will not be changed' + gen(max_tokens=10)
# lm did not 'see' anything generated by lm2
lm += 'More content here' + gen(max_tokens=10)
```

**Comment by AtharvanDogra** [comment]
Hi, i've tried using this. But when I'm running the code on a terminal, it still gives this output which I actually dont want.

![image](https://github.com/guidance-ai/guidance/assets/54113536/600ea668-aa2a-4377-a7e6-3f2c0e10766d)

**Comment by AtharvanDogra** [comment]
I have also tried the other way round

![image](https://github.com/guidance-ai/guidance/assets/54113536/8e8351aa-cd5d-41bc-a8d7-b9ea22935f7c)

**Comment by AtharvanDogra** [comment]
Nevermind, found it. For anyoe else looking for this in the future, use `echo=False` argument while initiating model from `guidance.models` 

#506
