### ISSUE TITLE
max_token ignored in remote models if greater than max_streaming_tokens

### ISSUE THREAD

**Issue by adamgordonbell** [guidance-ai/guidance#607]
**The bug**
gen(max_token=XXX) is ignored in remote models.

**To Reproduce**
- Set max_token great than 1000, the current hard coded amount. You will only get 1000 tokens back.

You can see here that max_streaming_tokens, at the model level is always used and not max_token passed to gen:
https://github.com/guidance-ai/guidance/blob/main/guidance/models/_openai.py#L203

**Comment by slundberg** [comment]
Hmm, max_tokens is something that gets embedded into the grammar, so it causes the token stream to break early. It seems to be working for me, but perhaps I am missing something?

<img width="417" alt="image" src="https://github.com/guidance-ai/guidance/assets/3740613/64cb400a-cdac-4f8f-8660-0bf0bb7e3a5d">

**Comment by SuperMasterBlasterLaser** [comment]
I've also noticed this problem when working with local AWQ models.

I'm using [Kunoichi-7B-AWQ](https://huggingface.co/TheBloke/Kunoichi-7B-AWQ) and loading it in this way:

```python
from lore import Lore
from guidance import models, gen, select, one_or_more
from transformers import AutoTokenizer
from awq import AutoAWQForCausalLM
import random
from jinja2.loaders import FileSystemLoader
from jinja2.environment import Environment
import requests

path = ".\TheBloke_Kunoichi-7B-AWQ"

captialize_regex = r"([A-Z][a-z]*\s*)+"

newline = "\n"

# This loads from somewhere else
card_prompt = ...

card_type = 'CREATURE'

result_prompt = f'''Card type: {card_type}
Realms: {one_or_more(select(location["realms_main"] + location["realms_secondary"], name="card_realms", list_append=True))}
'''

if card_type == 'CREATURE':
    result_prompt += f'''Race: {select(location["races"], name="card_race")}
    Gender: {select(["MALE", "FEMALE", "BOTH", "NO_GENDER"], name="card_gender")}
    Body type: {select(["HUMANOID", "NON_HUMANOID"], name="card_body_type")}'''

result_prompt += f'''Card Name: {gen(regex=captialize_regex, max_tokens=15, name="card_name", temperature=0.7)}
Description: {gen(max_tokens=128, temperature=0.7, name="card_description")}
'''

card_prompt += result_prompt

llama2 += card_prompt

print(llama2)
```

The main problem is that when I launch this, the code just hangs, and at last, throws an exception that it exceeded maximum context. While initial prompt may have about 2K tokens that looks strange, because the max context is 8K tokens. It seems that parameter `max_tokens` is being ignored and requires explicit `stop` parameter.

**Comment by adamgordonbell** [comment]
I found that this does work, and I was just misunderstanding how it works. You need to use both max_token, which controls when the grammar cuts things off and max_streaming_tokens which controls the api and when it stops. It's a bit confusing, but does work, so i will close this.

@SuperMasterBlasterLaser sounds like a different issue that you have.
