### ISSUE TITLE
phi-2 issue

### ISSUE THREAD

**Issue by ilmarinen** [guidance-ai/guidance#681]
**The bug**
List index out of range error when attempting to get a generation from phi-2

Traceback:

  File "evaluate_success.py", line 238, in evaluate_phi2_constrained_gsm8k
    response = model + prompt + gen("reason", max_tokens=220) + "\n" + "Answer: " + gen("answer", regex='\d+')
  File "/home/xfernandes/code/envs/venv/lib/python3.8/site-packages/guidance/models/_model.py", line 302, in __add__
    out = lm._run_stateless(value)
  File "/home/xfernandes/code/envs/venv/lib/python3.8/site-packages/guidance/models/_model.py", line 465, in _run_stateless
    for new_bytes, is_generated, new_bytes_prob, capture_groups, capture_group_log_probs, new_token_count in gen_obj:
  File "/home/xfernandes/code/envs/venv/lib/python3.8/site-packages/guidance/models/_model.py", line 819, in __call__
    sampled_token = self.tokens[sampled_token_ind]
IndexError: list index out of range

**To Reproduce**

```python
from guidance import models


model = models.Transformers(
    "microsoft/phi-2",
    echo=False,
    device="cuda:0",
    trust_remote_code=True)

prompt = "\n1. Please answer the following question:\nQuestion: Janet’s ducks lay 16 eggs per day. She eats three for breakfast every morning and bakes muffins for her friends every day with four. She sells the remainder at the farmers' market daily for $2 per fresh duck egg. How much in dollars does she make every day at the farmers' market?\n\n2. Break up your answer to the question in (1) into a series of simple steps.\n3. Write each of the steps down on a separate line.\n4. Write out the final answer to the question, which should be a single number.\n\nWrite out your response below"

response = model + prompt + gen("reason", max_tokens=220) + "\n" + "Answer: " + gen("answer", regex='\d+')
```

**System info (please complete the following information):**
 - OS: Ubuntu
 - Guidance Version: 0.1.10

**Comment by riedgar-ms** [comment]
Just trying now with the infrastructure in #674 .... I do note that "Janet's" uses a different apostrophe, which looks rather like the one in `test_unicode2()`.... which was giving me trouble in that PR

**Comment by riedgar-ms** [comment]
Can confirm, it's the apostrophy in "Janet's" - changing to a regular apostrophe allows the code to run (although putting a `max_tokens` on the second `gen()` also helped)

**Comment by Harsha-Nori** [comment]
Interesting! Can we check how the `phi-2` tokenizer handles the special apostrophe character? Am mid-flight at the moment with trickle internet or I'd try it myself, but my HF model download is failing.

**Comment by riedgar-ms** [comment]
Note, this is likely the same underlying issue as #682

**Comment by riedgar-ms** [comment]
Experimenting with calling Phi-2 directly, the following works (until the final `assert False`):

```python
def test_unicode_temp():
    from transformers import AutoModelForCausalLM, AutoTokenizer
    import torch

    model = AutoModelForCausalLM.from_pretrained("microsoft/phi-2", torch_dtype=torch.float32, trust_remote_code=True)
    tokenizer = AutoTokenizer.from_pretrained("microsoft/phi-2", trust_remote_code=True)
    
    prompt = "Janet’s ducks lay 16 eggs per day"

    inputs = tokenizer(prompt, return_tensors="pt", return_attention_mask=False)
    outputs = model.generate(**inputs, max_length=200)
    text = tokenizer.batch_decode(outputs)[0]
    print(text)
    assert False, text
```

**Comment by slundberg** [comment]
The problem is that the transformer model returns 51200 logits when you call it but `len(tokenizer.get_vocab())` is only 50295...

**Comment by slundberg** [comment]
Okay after a lot of digging the bigger problem here is that the Phi2 tokenizer does not have the `byte_decoder` attribute, this means we don't get tokens that are not valid strings correctly into the vocab...(they are just the � string)

I am not sure how to fix this, there must be some way to extract the actual byte-string tokens from the tokenizer but I don't know how. @riedgar-ms if you have any ideas let me know :)

**Comment by riedgar-ms** [comment]
Side note: I have just spotted that we were getting a warning
`Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.`
