### ISSUE TITLE
Possible issue with interegular? (Character Classes like [.?!, ])

### ISSUE THREAD

**Issue by michael-conrad** [guidance-ai/guidance#710]
**The bug**

When I specify a regex with `r"[.?!, ]"`, the output of the LLM becomes unconstrained.

**Comments**

I have to use `r"[\.\?!, ]"` to get the desired behavior. It is my understanding that a `.` in a character class bracket set is supposed to be treated as a literal, not as a match anything?

See also: [https://stackoverflow.com/a/19976308/12407701](https://stackoverflow.com/a/19976308/12407701)

**Comment by hudson-ai** [comment]
This should be addressed by #854 -- planning on merging soon :)
