### ISSUE TITLE
Pin version of llama-cpp-python

### ISSUE THREAD

**Issue by michael-newsrx** [guidance-ai/guidance#711]
**Is your feature request related to a problem? Please describe.**

I'm frustrated by breaking changes in llama-cpp.

**Describe the solution you'd like**

Pin llama-cpp-python to version 0.2.56 as 0.2.57 breaks everything again, and in fact won't even load models on my system due to pinned memory errors. With an RTX-4090 card on a 64GB system.

**Comment by paulbkoch** [comment]
Hi @michael-newsrx -- The llama-cpp-python breaking changes are certainly annoying, however llama-cpp-python is not included as a Guidance dependency since Guidance can work with multiple models and including them all would be fairly heavyweight.

**Comment by paulbkoch** [comment]
Closing this issue since we have no plans to add llama-cpp as a dependency.  Please feel free to reopen if you can think of any other solutions that Guidance could employ to mitigate llama-cpp instability issues.
