### ISSUE TITLE
Production example?

### ISSUE THREAD

**Issue by jloganolson** [guidance-ai/guidance#73]
I would really appreciate an example for how we should use this in an application. Like it's been awesome in a notebook, but how should I hook this up in a flask application as a streaming REST endpoint (or similar sort of 'headless' python script)?

**Comment by jean1190** [comment]
I am interested as well...

**Comment by slundberg** [comment]
Check out #129 now as well.

**Comment by marcotcr** [comment]
I think the new [release](https://github.com/guidance-ai/guidance/discussions/429) makes this all much easier, as what you have is basically python code. Please check it out :)
