### ISSUE TITLE
Non-interactive mode

### ISSUE THREAD

**Issue by wendlerc** [guidance-ai/guidance#760]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when the guidance library outputs stuff in std out or delete stuff that I print there...
I tried `with silent():` but in that case my outputs still get deleted. 

**Describe the solution you'd like**
I'd like to do a constrained generation and just get the result with no sideeffects.

Sorry if this feature already exists, I did not find it in the readme and examples.

**Comment by Harsha-Nori** [comment]
Hey @wendlerc, sorry about that. You can suppress the streaming outut by setting `echo=False` in the init of any `guidance.models` object, eg:

```python
lm = models.Transformers(model_id, echo=False)
```

I'll try to find a nice place to add this to the README too.

**Comment by wendlerc** [comment]
Thank you so much that's exactly what I needed!
