### ISSUE TITLE
`python setup.py build` not working

### ISSUE THREAD

**Issue by slundberg** [guidance-ai/guidance#801]
**The bug**
If we run `python setup.py build` we get an error `ModuleNotFoundError: No module named 'setuptools_rust'`

Note that if I run `pip install --editable .` that works.

@paulbkoch or @riedgar-ms is this something specific to my system or should we throw an error for the setup.py install route (and point people to pip or other pyproject.toml based package manager)?

**Comment by Harsha-Nori** [comment]
Might just be a matter of adding `setuptools_rust` as a dependency? https://pypi.org/project/setuptools-rust/

**Comment by paulbkoch** [comment]
I think Harsha is correct.

**Comment by paulbkoch** [comment]
And other possibility is that something else in the optional [test] tag is installing setuptools_rust.  I haven't looked yet, but I have a hunch.

**Comment by Harsha-Nori** [comment]
Ok, upon looking into this a bit more, it's actually quite painful to force that setup.py dependencies get installed before actually evaluating the rest of the setup script. I tried a combination of lazy imports and found out I really overestimated the `setup_requires` field...

Seems like pointing people towards `pip` is definitely an easier, more modern method. Implemented this in https://github.com/guidance-ai/guidance/pull/805
