### ISSUE TITLE
Allow generating arbitrary (schemaless) JSON

### ISSUE THREAD

**Issue by wjn0** [guidance-ai/guidance#887]
**Is your feature request related to a problem? Please describe.**
There's a few distinct motivations for this:
* APIs such as OpenAI allow users to request only valid JSON be generated sans schema, so in some sense this would give feature parity for local LLMs.
* Large JSON schemas often include "arbitrary" properties, e.g. properties that are allowed to be any valid JSON value: https://json-schema.org/understanding-json-schema/basics#hello-world!

**Describe the solution you'd like**
Ideally, calling `guidance.json` without a schema should allow arbitrary JSON to be generated.

Additionally, this would allow us to support the empty schema when nested within a larger schema (my real issue).

**Comment by hudson-ai** [comment]
Another great feature request -- I was also thinking about this earlier this week..!

I'll think about this a bit more, but I don't think it would be too difficult to implement -- rather than raising an exception when we hit a node without a `type` field, we could just `select` from all valid types.

@riedgar-ms thoughts?

**Comment by riedgar-ms** [comment]
It's an interesting thought, although how exactly are you considering doing the selection? If you use a guidance `select()` you will certainly make the generation stateful. Support for a regular PRNG selection might make it stateful too (and would certainly need server-side support).

Could we just write something simpler, given that we know that JSONs are dictionaries where the keys are quoted strings, and the values are ints, floats, strings, a list of JSON objects or a whole new JSON object?

If we do shoe-horn such capability into the existing JSON API, I'd suggest making it off by default. Make users acknowledge that their schema isn't fully defined.

**Comment by hudson-ai** [comment]
@riedgar-ms this is what I meant by selecting from all valid types -- I think it's consistent with what you suggest. I don't think it's shoe-horning though, as afaik, `{}` is truly the "anything goes" specification as far as json schemas are concerned.

First pass at an implementation here. I probably missed a corner case, but this may honestly be almost good-to-go once I add some tests.
https://github.com/hudson-ai/guidance/tree/json_any

**Comment by wjn0** [comment]
_Very_ cool implementation with the "ghost" any definition -- this was the lines along which I was thinking as well :)

**Comment by riedgar-ms** [comment]
That look like it avoids the pitfalls I was worried about.

**Comment by hudson-ai** [comment]
Cool, I'll write up some tests if y'all are happy with the general idea :)
