### ISSUE TITLE
Cannot import guidance w/ vertexai due to protobuf version mismatch

### ISSUE THREAD

**Issue by Harsha-Nori** [guidance-ai/guidance#941]
**The bug**

Guidance import currently fails with `vertexai` installed:

```python
import guidance
```
-> 
<img width="973" alt="image" src="https://github.com/guidance-ai/guidance/assets/5302119/8d6949a5-82cc-4140-8520-39f67425fcec">

VertexAI has a pinned dependency on protobuf == 4.25.3, which is incompatible with the new fix introduced in https://github.com/guidance-ai/guidance/pull/937

**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.

```pip install --upgrade google-cloud-aiplatform```
```python
import guidance
```

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): MacOS
 - Guidance Version (`guidance.__version__`): main branch at b72c8cdbbc5b8666628a54bbaa1a35c7eb92b496
 
 
 @nking-1 @hudson-ai

**Comment by nking-1** [comment]
Are we stuck with protobuf 4.25.3 because of this? I don't think the new version is a strict requirement for the fix in https://github.com/guidance-ai/guidance/pull/937 to work. I will need to look into how to install a specific version of `protoc` if we're going to be pinned to a version.

**Comment by Harsha-Nori** [comment]
I think we are based on how vertexAI seems to manage dependencies on their python package

@slundberg and @mmoskal for awareness

**Comment by nking-1** [comment]
I see. I think I can fix this by generating the protobuf definitions with `protoc 25.x`, based on the version chart shown here: https://protobuf.dev/support/version-support/#python

**Comment by nking-1** [comment]
A fix is pending in https://github.com/guidance-ai/guidance/pull/928

**Comment by hudson-ai** [comment]
@Harsha-Nori should be fixed after merging in #946 :)
