### ISSUE TITLE
Telegram or Discord dedicated channels?

### ISSUE THREAD

**Issue by michael-conrad** [guidance-ai/guidance#955]
**Is your feature request related to a problem? Please describe.**

Looking for a place to try and get help in an interactive fashion.

**Describe the solution you'd like**

Telegram group or Discord channel.

**Describe alternatives you've considered**

Google searching

**Comment by riedgar-ms** [comment]
We have a discord channel:
https://discord.com/channels/1113626258182504448/1240509960488747038

**Comment by michael-newsrx** [comment]
**NO TEXT CHANNELS**

**Comment by michael-conrad** [comment]
> We have a discord channel: https://discord.com/channels/1113626258182504448/1240509960488747038

Link does not work.

**Comment by themantalope** [comment]
Link does not work. Please update the link if possible, would like some guidance (pun intended) on using the package.
