### ISSUE TITLE
Add Inline Source Syntax Highlighting in VSCode for Microsoft's Guidance

### ISSUE THREAD

**Issue by Elijas** [guidance-ai/guidance#99]
<img width="561" alt="examples" src="https://github.com/microsoft/guidance/assets/4084885/ac51fbc9-125e-469a-8f24-6ee4922ce4df">

**Is your feature request related to a problem? Please describe.**
Users working with Microsoft's Guidance language in VSCode could benefit from a more seamless experience when it comes to inline syntax highlighting and language support.

**Describe the solution you'd like**
I propose developing a VSCode extension that integrates Microsoft's Guidance language, providing inline syntax highlighting and other language-specific features for a better user experience.

**Describe alternatives you've considered**
Waiting until guidance achieves a better adoption to do that, and focus on the core functionality of it for now.

**Additional context**
The [samwillis/python-inline-source](https://github.com/samwillis/python-inline-source) project enables inline syntax highlighting of strings in Python source files for multiple languages using type annotations. This is where the screenshot at the top is taken from. But adding the library as a dependency wouldn't even be needed, as the equivalent effect of having it could be achieved by just having `from guidance import sourcetype`, where `sourcetype = Annotated[Annotated[str, 'source_code'], 'guidance']`.

**Comment by slundberg** [comment]
This would be great, and any PR on this would be most welcome!

I looked into doing this but didn't have enough time to implement it yet. The one downside of using the python-inline-source approach is that you have to always define your programs as separate string variables instead just giving them as literals to the guidance call. But it still seems like a great place to start.

**Comment by Elijas** [comment]
@slundberg
I've been considering an alternative approach that could avoid having the source as a separate string. As a side effect, this would also eliminate the need for the third-party library, [samwillis/python-inline-source](https://github.com/samwillis/python-inline-source).

Here's a rough draft of the idea (please note that I haven't tested this code yet):

```python
from typing import Annotated, Union
try:
    from typing import Annotated
except ImportError:
    from typing_extensions import Annotated

source_code = Annotated[str, 'source_code']
guidance_source_code = Annotated[source_code, 'guidance']

def guidance(src: Union[str, guidance_source_code]):
    ...

guidance("""<guidance code here has its syntax highlighted>""")
```
I'd love to hear your thoughts on this approach.

**Comment by marcotcr** [comment]
Just commenting that I too would love this :)

**Comment by slundberg** [comment]
Great idea! I had not thought about typing the arg. `from guidance import sourcetype` I don't think I fully follow yet. But I am happy with [samwillis/python-inline-source](https://github.com/samwillis/python-inline-source) since it seems like installing an extension for the source code highlighting would be no trouble

**Comment by marcotcr** [comment]
In the new [release](https://github.com/guidance-ai/guidance/discussions/429) we did away with template strings, and now use python's f-strings. Thanks so much for your initial work on this!
