### ISSUE TITLE
Enhance docs

### ISSUE THREAD

**Issue by Mihaiii** [guidance-ai/guidance#991]
IMO the refactoring that introduced `__add()__` getting called for inference makes very little sense.

I just want to loop through a list, call the llm, await the response, and store the response as a string. It's the most simple, basic thing, but the library makes everything too hard now. How to do it? I don't care about streaming, just the end string.

**Comment by Harsha-Nori** [comment]
Hey @Mihaiii, apologies that the refactor may have been a bit confusing. I'm not completely sure I'm interpreting your question correctly, but here's a quick example that might help.

```python
from guidance import guidance, models, gen, select, user, assistant, system

# Load the model -- note that trust_remote_code is a model specific kwarg, and echo suppresses the print to console
lm = models.Transformers("microsoft/Phi-3-mini-4k-instruct", trust_remote_code=True, echo=False) 

@guidance
def get_origin(lm, name):
    with system():
        lm += f"""The user will provide you with their name. Your task is to provide the most likely country of origin for that name.
        Your options for the country of origin are 'United States', 'India', and 'Brazil'."""
    with user():
        lm += f"Name: {name}"
    with assistant():
        lm += "The country of origin is most likely: " + select(["India", "Brazil", "United States"], name="country")
    return lm

# Apply the function on a list of items
name_list = ["Harsha", "Scott", "Marco"]
countries = []
for name in name_list:
    classification = lm + get_origin(name)
    countries.append(classification['country']) # Extract the response for the `select` statement here.

# Print the stored outputs
for name, country in zip(name_list, countries):
    print(name, country)
```
<img width="444" alt="image" src="https://github.com/user-attachments/assets/d00d328c-ea8e-4b86-9ff4-c871ca99bccb">

We said we wanted the output of the `select` to be named `country`, so the output of just the select statement is stored in `classification['country']`. If you want to see the entire state of the lm, you can `print(str(classification))`, which shows you exactly how guidance is building the prompt (with all special tokens for chat, etc.) and sending it to the model:

<img width="973" alt="image" src="https://github.com/user-attachments/assets/5ce5c9b5-730e-408c-ad36-4a3897277bca">

If you want more granular control over exactly what strings you want extracted, you can use the `capture` function to assign a variable name to an entire range of generation. Hope this helps and happy to clarify further! Would greatly appreciate your suggestions on how to improve the docs here too if this was helpful :).

**Comment by Mihaiii** [comment]
Thanks for the example, it is helpful, yes! 🙏
I'm using a json schema to generate the response and I'm interrsted only in the response the assistant provided. I could parse the str version of `lm`, but there must be some better way of getting that. :)

**Comment by Harsha-Nori** [comment]
Got it. Here's a quick example of getting a neat python object back out of the guidance `json` function. I'm using Pydantic here but you could also pass a json_schema to the exact same arg.

```python
from guidance import json as g_json
from pydantic import BaseModel

class Step(BaseModel):
    explanation: str
    output: str

class MathResponse(BaseModel):
    steps: list[Step]
    final_answer: str

@guidance
def math_mate(lm, problem):
    with system():
        lm += "You will be provided with a math problem. Write out your steps to solve the problem in JSON format, followed by the answer as a 'final_answer'."
    with user():
        lm += f"Here is my math problem: {problem}"
    with assistant():
        lm += g_json("json_answer", schema=MathResponse)
    return lm

math = lm + math_mate("(22 + 8) * 5")
```
<img width="1089" alt="image" src="https://github.com/user-attachments/assets/0a27f80b-2a16-48d2-a113-8c082cce0942">

The JSON generated is now a string inside the `json_answers` variable on the `math` LM object. To turn this into a python dict, we can just use the standard library `json.loads()`, and then do whatever we want with it:

```python
import json
pydict = json.loads(math['json_answer'])
print(pydict)
```
<img width="1132" alt="image" src="https://github.com/user-attachments/assets/ecee28a7-5ecb-4ef4-9b55-1ebcbf4f60e0">

**Comment by Mihaiii** [comment]
Ah, I see. Thank you very much!
I'm closing this one. Thanks again for the provided examples and the detailed response!
